### ISSUE TITLE
package '@fontsource/quicksand' not found on NPM

### ISSUE THREAD

**Issue by AnfalHussain** [DecliningLotus/fontsource#1004]
### Description

I cannot install the package from npm and I get the following error: : 
`error An unexpected error occurred: "https://registry.yarnpkg.com/@fontsource/quicksand/-/quicksand-4.5.12.tgz: Request failed \"404 Not Found\"". `

<img width="1647" alt="Screenshot 2024-12-08 at 9 43 48 PM" src="https://github.com/user-attachments/assets/eb5f45c9-89a5-496c-b528-f6c23484f418">

**Comment by imphil** [comment]
public-sans is gone as well (https://www.npmjs.com/package/@fontsource/public-sans).

Edit: We are in an NPM maintenance window (https://status.npmjs.org/), so maybe it resolves itself after a while.

**Comment by AnfalHussain** [comment]
> public-sans is gone as well (https://www.npmjs.com/package/@fontsource/public-sans).
> 
> Edit: We are in an NPM maintenance window (https://status.npmjs.org/), so maybe it resolves itself after a while.

Thank you, I think that is the cause of the issue, I tried other random packages on npm all are returning 404
