### ISSUE TITLE
add type declarations for typescript developer.

### ISSUE THREAD

**Issue by mohamad-es** [DecliningLotus/fontsource#1005]
### Describe the feature you'd like to request

At this time, most projects with User interfaces with React or Next use TypeScript, and when developers try to add this package to a TypeScript project, they face an error. I hope you consider my suggestion.

thank you for your time.

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added TypeScript declaration files to both the CLI and Generate packages to improve TypeScript support for React and Next.js projects.

You can review changes in this commit: https://github.com/kkpo4553/fontsource-fontsource-1005/commit/4579b69c59260f806c9de468d6b82b4d290852e2.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by mohamad-es** [comment]
okay, thank you for your response.
