### ISSUE TITLE
woff2 files are missing for roboto-condensed-all

### ISSUE THREAD

**Issue by rushenn** [DecliningLotus/fontsource#345]
Can you add woff2 files for `all` variant in `roboto-condensed`

**Comment by ayuhito** [comment]
The all file is only available for WOFF files as it's a fallback for the subsetting we and whether a browser doesn't support the unicode-range selector. 

This matches how Google serves their fonts and I'm only downloading what they give us. Thus, I'm not going to accept this issue.

You are more than welcome to convert the woff file yourself for your own use, however.
