### ISSUE TITLE
Font Request: Iosevka variants Aile, Etoile, Curly

### ISSUE THREAD

**Issue by teauxfu** [DecliningLotus/fontsource#359]
Iosevka's primary typeface was added in #288. Thanks!!! :+1: 
https://fontsource.org/fonts/iosevka

I'd like to request the addition of some of its variants which are available as unique font families.
There are a lot of variants, and I understand that resources are limited.
So, I'm just requesting these that I know I would use (but they are all pretty good!)

**Font Names**

- Iosevka Aile
- Iosevka Etoile
- Iosevka Curly __*__

**Link to font source**

https://github.com/be5invis/Iosevka/blob/master/PACKAGE-LIST.md

**Link to font license**
SIL v1.1: https://github.com/be5invis/Iosevka/blob/master/LICENSE.md

**Additional context**
__*__: `Iosevka Curly` is a variant of `Iosevka` (monospaced) that is released as a separate font but also seems able to be applied via a css parameter as demonstrated here. I don't know if this kind of duplication is a problem.
![image](https://user-images.githubusercontent.com/1144380/135516837-9e2c39e4-ff1f-4e17-8629-ceef16da8b34.png)

**Comment by teauxfu** [comment]
Sorry if I've overlooked it, but is there some documentation on what the appropriate steps are for making a PR to add a font? 
I'd be glad to help out on this if I knew where to start

**Comment by ayuhito** [comment]
> Sorry if I've overlooked it, but is there some documentation on what the appropriate steps are for making a PR to add a font? I'd be glad to help out on this if I knew where to start

Apologies for the lack of response. I actually do need to make documentation regarding adding fonts so people can make PRs, especially since nowadays I have been very pressed for time with university to easily do this myself.

What I'm going to do is make the relevant documentation for submitting new fonts within the next few hours (as well as cleaning up some very messy code to do so), hopefully, to get this completely out of the way.

**Comment by ayuhito** [comment]
@teauxfu, I added documentation [here](https://github.com/fontsource/fontsource/tree/main/scripts/generic). Let me know if there are any questions.

The fontId's we should go for are:
- iosevka-aile
- iosevka-etoile
- iosevka-curly (it should be fine to include this one)

With the subset for all files to be `latin-ext` and defSubset be set to `latin-ext`.

Hope that helps, and thank you!

**Comment by teauxfu** [comment]
Hey @DecliningLotus thanks for the clear documentation. I have a few follow up questions for you

I'm having some issues generating fresh css files, but I feel like this should be an easy fix for Iosevka since it comes with CSS files very nearly identical to what Fontsource expects. Also, I think whatever process was used for packaging the Iosevka font already in `/packages/` would be informative here since not too much seems to have changed (excepting the omission of .woff files)

In particular, I'm getting a lot of NaN values where we expect a weight in the font file names.

![image](https://user-images.githubusercontent.com/1144380/142675835-bcddb22b-4dbb-48da-9f34-ce264320c283.png)

This may be related to either

- Iosevka only building woff2 files 
- Iosevka using weight names that are not defined in `scripts/generic/renamer.ts`
- something else

Please advise if there is any relevant info or docs that would help before I put too much time into manually fixing this. Ideally I'd like to write a helper script to automate this process across the Iosevka fonts going forward

As an example of the css that Iosevka ships prepackaged with: 
https://github.com/teauxfu/fontsource/blob/iosevka-aile/scripts/generic/files/iosevka-aile.css

As an aside, this makes me wonder if we should be titling these as "Iosevka Foo Web" as the css seems to suggest, or just "Iosevka Foo" since web is implied. What do you suggest?

#394

**Comment by ayuhito** [comment]
Unfortunately, the process is typically very laborious and tedious for fonts like this.

The renamer only does a little to help, but usually I'd then have to use a tool like PowerRenamer to rename a bunch of the font files in the required format before using the packager. Furthermore, if there are only WOFF2 files, we'd need to manually convert and include the WOFF equivalent files into the mix.

If you have any suggestions for helper scripts that can make the process easier, I'm always open to that. It's really a matter of getting the font files in the correct name format, and then everything is smooth sailing.

Regarding the naming, I think it's better not to include the "web" to remain consistent with the original Iosevka font package on Fontsource.

**Comment by ayuhito** [comment]
Closed in fontsource/font-files#1.
