### ISSUE TITLE
Add ttf/otf files to fontsource

### ISSUE THREAD

**Issue by jwr1** [DecliningLotus/fontsource#371]
I think we should add the ttf/otf files back into fontsource (without publishing them to npm). That way they can be accessed and downloaded through the API, and once we get it set up, people could also download them through the website. woff and woff2 files are very useful for websites, but if someone wanted to easily download a font from fontsource and install it or use it on their desktop or mobile device, they would have to have ttf/otf files.

**Comment by ayuhito** [comment]
I don't know when this would be ready, but google/fonts#3880 would be likely to add backwards support all the way to eot and svg formats.

I'm unsure if we should throw in the effort for this when the Google API will eventually be revamped with some clear specifications. We could then adapt our website to use their API for downloads.

**Comment by alerque** [comment]
I think this should be re-opened, it was delayed but not stale.

**Comment by teauxfu** [comment]
Maybe not the right issue but a relevant discussion:

With respect to the linked PR I'll play devil's advocate:
I think having the option of accessing those files is great, but perhaps at some point the responsibility should shift such that if users want to install a font locally (TTF, TTC, etc) then they should consult the linked relevant official docs for that font. Or, in other wording -- what is the purpose / limit of scope for Fontsource? Is a font only eligible for inclusion if it can be provided in all these formats (WOFF, WOFF2, TTF)?

I'm working on packaging some Iosevka variants right now. Those webfont files are released only as WOFF2 and TTF, and maybe soon only as WOFF2 by default. Sure, font format conversion packages definitely exist... but I'm wondering how many extra parts are necessary/worthwhile. 

Could the API be structured such that font entries could be queried for or hinted at from the interface?
