### ISSUE TITLE
Difference in anti-aliasing for `Open Sans` fonts

### ISSUE THREAD

**Issue by thasmo** [DecliningLotus/fontsource#383]
There seems to be a difference in quality of anti aliasing for Open Sans fonts comparing the fonts provided by `@fontsource/open-sans` and the fonts served via the hosted `Google Fonts` fonts. (This also happens for a specific font-size range only; ~ 20px)

**fontsource package**
Characters are not anti-aliased properly and seem very "rough".
![image](https://user-images.githubusercontent.com/184284/139528427-52f39e3f-ef78-431e-bfb8-a79d60142241.png)

**Google Fonts web service**
Characters are anti-aliased properly and appear "smooth".
![image](https://user-images.githubusercontent.com/184284/139528440-17c2f64d-7b5d-45af-815c-11d335e79ed6.png)

What is the reason for this? Is the `Google Fonts` web service serving a different version?

The screenshots were made from a website displayed in Firefox on Windows.

**Comment by thasmo** [comment]
Oh, I just looked it up and it seems that Google is serving `v27` while `fontsource` is distributing `v26`. How/when does fontsource update new font versions?

**Comment by ayuhito** [comment]
Every Sunday Fontsource updates the repository. We should automatically see a published fix tomorrow.

**Comment by thasmo** [comment]
Thanks! Are daily builds too complicated/expensive?

**Comment by ayuhito** [comment]
I could look into maybe doing it bi-weekly? Daily builds seem a bit excessive and I can't quite put it into words why I feel uncomfortable about it. Also, Google themselves post their updates in batches so many builds would just be redundant.

Back when we used Lerna, builds were a bit too unreliable and very slow (would take an hour) in the publish stage for me to do it more regularly. That's not an issue now though with the custom publisher.

**Comment by ayuhito** [comment]
Actually before I make a change like that, I do need to make some formatting fixes for the publisher that pollute our build commits.

**Comment by ayuhito** [comment]
Fixed in 7b9ec9e21367fd5e9ae475eb89e1a686f05618b8. I've noted the publisher changes separately.
