### ISSUE TITLE
Replace default Variable Font Names with a space

### ISSUE THREAD

**Issue by ayuhito** [DecliningLotus/fontsource#385]
Currently, variable fonts generate their own individual `font-family` name as something such as `RobotoVariable` or `Open SansVariable`.

The lack of a space in between is a huge oversight and I can understand why it can be somewhat confusing. The newly generated names, for example, would be `Roboto Variable` or `Open Sans Variable`.

**Comment by thasmo** [comment]
FYI; this already works that way (space between name and suffix) in the [proposal](https://github.com/fontsource/fontsource/discussions/384).

**Comment by ayuhito** [comment]
> FYI; this already works that way (space between name and suffix) in the [proposal](https://github.com/fontsource/fontsource/discussions/384).

Only for Sass. This is a project-wide change (such as the default CSS files already provided).

**Comment by LasseRosenow** [comment]
Based on how huge the browser support for variable fonts is, I would like it even more if the variable fonts just use the same name as the non variable fonts.

We already make the decision on what kind of font we use, by importing the variable.css file.. But also having to replace all the `font-family: some-font` with `font-family: some-fontVariable` is unnecessary work :(

The reason as to why I have to replace those font-family attributes is a result of how our company works. I usually get css files from designers and they do not use this repo :( But I also cannot blame them to use the "correct" font names and not some suffixes which are special to this repo alone.

**Comment by ayuhito** [comment]
@LasseRosenow, I'm not very opposed to that actually. 

However, the original reason why the additional suffix was included was to help differentiate the font files to fit this [recommendation](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide#working_with_older_browsers) from MDN. 

Google Fonts doesn't need to differentiate its font name since it will serve the compatible font based on the user agent.

**Comment by LasseRosenow** [comment]
@DecliningLotus 

Okay then what about using this @supports stuff inside the default import. like when you just import `import "@fontsource/open-sans"` it could be somwhat like this
```css

@supports (font-variation-settings: 'wdth' 115) {
  @font-face {
    font-family: "open-sans";
    src: url(open-sans-variable.woff2); /* <-- variable font */
  }
}

@supports not (font-variation-settings: 'wdth' 115) {
  @font-face {
    font-family: "open-sans";
    src: url(open-sans-400.woff2); /* <-- non variable font */
  }
}

```

This way we could use the default import, which is nice and we would get variable fonts for modern browsers and non variable fonts for older browsers.

And if we want to force what we want to have, we can still import the variable font via variable.css etc.

**Comment by ayuhito** [comment]
It sounds like a reasonable idea, although I feel fairly uneasy to make it a default setting since I'm unsure how it will affect the tens of thousands of projects downstream in niche unexpected ways. That's why it's always been an "opt-in" solution for developers, rather than "opt-out".

I think there will be a time where variable fonts becoming a default option happens, but I'd rather wait for Google Fonts to become more aggressive with that idea themselves before following suit.

Generating these automatically in #234 behind a flag is also something very doable.

**Comment by LasseRosenow** [comment]
> It sounds like a reasonable idea, although I feel fairly uneasy to make it a default setting since I'm unsure how it will affect the tens of thousands of projects downstream in niche unexpected ways. That's why it's always been an "opt-in" solution for developers, rather than "opt-out".

I mean it would be a breaking change of course, but we could increase the major version number of all packages, this way none of those thousands projects would be affected



> I think there will be a time where variable fonts becoming a default option happens, but I'd rather wait for Google Fonts to become more aggressive with that idea themselves before following suit.

I'm not sure what you mean with "Google Fonts to become more aggressive" I think they are somewhat too aggressive as they just updated hundreds of fonts to variable fonts without asking anyone and shipping them by default. Right now you always get variable fonts if the font you are using has a variable version and your system is not opted out for some reasons like I think Firefox on Windows right now, even though they are reevaluating this right now I think ^^ 
So what I mean is, what is your idea on how Google could be pushing variable fonts more aggressively?


#234 sounds very interesting btw.!! :)

**Comment by ayuhito** [comment]
I actually agree with your points now that you mention those details. But now I recall why this is a very messy problem.

We actually did previously serve VFs as a default import (unintentionally), which was discovered when one user experienced an issue discussed in #142. Google Fonts does serve VFs by default which got passed on. I "fixed" that since users were importing duplicate font files as a result of that unintended behaviour described in [#142 (comment)](https://github.com/fontsource/fontsource/issues/142#issuecomment-829358772).

We could make a breaking change and make VFs a default import stating you only need to make one import to access all weights. But then what about non-VFs? The last thing I want to do is have two sets of default installation instructions across the entire project since that'll cause confusion. I'd rather have one default installation method, with opt-in variations rather than two defaults that differ per package. Sure it's not hard to make differing packages distinguishable... but I can guarantee people will get confused regardless. 

It's possible to merge all weights into one CSS file for non-VFs to make the installation method uniform repo-wide. But I've shot that down multiple times due to CSS file size concerns. e.g. [#289 (comment)](https://github.com/fontsource/fontsource/issues/289#issuecomment-890537646) I didn't mention it in that comment, but even for simpler fonts like Roboto (assuming it was non-VF), they'd still have unnecessarily large CSS files due to them having 6 different weights for 7 different subsets. Let's not also forget that VFs will have to include these large blocks of code regardless if we were to include the `@supports` fallback.

#234 is something that could account for all these edge cases. Perhaps it would make sense to prioritise that issue...
Alternatively, dynamically serving the correct CSS file using user agents just like Google Fonts, but in runtime is also a possible idea. But it would be framework dependent and require specific development for individual frameworks like React. The current Fontsource tries to be framework independent.

**Comment by ayuhito** [comment]
> Based on how huge the browser support for variable fonts is, I would like it even more if the variable fonts just use the same name as the non variable fonts.

Since we’re moving regular and variable fonts into separate packages (#589), I think all my previous concerns for your proposals are resolved. I’m happy to name each font the same!

**Comment by ayuhito** [comment]
In the end, I went back to using different names as we needed a reliable way to write [fallbacks](https://fontsource.org/docs/getting-started/variable#4-fallbacks). Released in [v5](https://fontsource.org/docs/getting-started/migrate-v5) 🎉

**Comment by fnlctrl** [comment]
Could there be an alternative css file that doesn't have the "Variable" suffix?

We're currently developing a rich text editor that supports fonts. By copying the content, HTML containing the "font-family: Some Font Variable" can be pasted elsewhere and this may not be cross-editor compatible - because other editors are more likely to support "Some Font" since it's the universal name, but not "Some Font Variable".

**Comment by ayuhito** [comment]
> Could there be an alternative css file that doesn't have the "Variable" suffix?

We can't generate more CSS files and pack it into the package. That would end up cluttering package directories even more.
 Instead, you can rewrite the `@font-face` files yourself e.g.
```css
@font-face {
  font-family: 'Abel';
  font-style: normal;
  font-display: optional;
  font-weight: 400;
  src: url(/node_modules/@fontsource/abel/files/abel-latin-400-normal.woff2) format('woff2'), url(/node_modules/@fontsource/abel/files/abel-latin-400-normal.woff) format('woff');
}
```
Or the prefix may be `npm:@fontsource...` or `~@fontsource`. I don't recall exactly what works, but I've seen it in the wild before so you may need to experiment a little.

However, for an RTE that supports many fonts, I wouldn't suggest self-hosting the fonts since your end package will have to bundle them in. You might be better off rewriting the `src` with a CDN link such as using Google Fonts or `https://cdn.jsdelivr.net/npm/@fontsource/roboto@5.0.0/files/abel-latin-400-normal.woff2` if you would prefer an alternative CDN.

**Comment by fnlctrl** [comment]
Will give that a try. Thanks!

~~As for the bundling part, it's fine as we're using vite that emits woff2 files to `dist/assets` which would eventually be served by cloudflare. We also use [CSS Font Loading api](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Font_Loading_API) to eager-load based on fonts used in content.~~ By rich text editor I meant an app for end-users, not a npm package - sorry for the confusion
