### ISSUE TITLE
Lato latin-ext is missing several characters

### ISSUE THREAD

**Issue by bycaldr** [DecliningLotus/fontsource#389]
**Describe the bug**
As Fontsource is using font files from Google Fonts, there is connected issue (https://github.com/google/fonts/issues/1564) with "missing" Lato font latin-ext characters.

**To Reproduce**
Test for example `Růžička` in Lato font preview. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8123172/140640806-0eac5769-210c-4795-b4cd-e954f6f48f40.png)

**Additional context**
I've solved issue in my project using oficial https://www.latofonts.com/lato-free-fonts/ source files. Maybe use of this font files would be the right solution to fix this issue.

PS I love using Fontsource in my projects and I'd like to contribute on this issue. I'm not sure if use of different source files than Google Fonts wouldn't go against fontsource patterns/standards. Thank you :v: !

**Comment by thasmo** [comment]
It seems that the development/release of "Lato 3.0" stalled. There's a recent related [issue about "Lato 3.0"](https://github.com/google/fonts/issues/3978).

**Comment by ayuhito** [comment]
Unfortunately, I don't think it's possible for us to manually change the source files ourselves for Google Fonts. The changes will wipe itself away next time we automatically build and publish.

It's best we wait for Google to resolve the issue themselves upstream.
