### ISSUE TITLE
Font Request: iA Fonts

### ISSUE THREAD

**Issue by tmm** [DecliningLotus/fontsource#391]
**Font Name**
- iA Writer Duo
- iA Writer Duospace
- iA Writer Mono
- iA Writer Quattro

**Link to font source**
https://github.com/iaolo/iA-Fonts

**Link to font license**
SIL OFL

**Additional context**
Happy to create a PR if it's okay to add these :)

**Comment by ayuhito** [comment]
@tmm, I don't have an issue including these fonts to the repo. Feel free to look at [this](https://github.com/fontsource/fontsource/tree/main/scripts/generic) if you want to have a go at making a PR for this.

**Comment by tmm** [comment]
@DecliningLotus created a PR :)
