### ISSUE TITLE
Font Request: ApfelGrotezk

### ISSUE THREAD

**Issue by stefee** [DecliningLotus/fontsource#393]
**Font Name**
ApfelGrotezk

**Link to font source**
http://collletttivo.it

**Link to font license**
SIL OFL

**Additional context**

**Comment by ayuhito** [comment]
Is there a link to the license directly? Does the font not have a GitHub repo?

**Comment by stefee** [comment]
The license is included with the download from the website. I don’t believe there is a repo.
