### ISSUE TITLE
How to prefetch or preload the fonts with next js? (Question)

### ISSUE THREAD

**Issue by MuriloDutra** [DecliningLotus/fontsource#403]
Hey guys, how are you?

I need a little help, how can I prefetch or preload the fonts with next js?

I tried the following code in _app.tsx and _documents.tsx, but it didn't work: 

```
<Head>
        <link
          rel="preload"
          href="@fontsource/montserrat/400.css"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="@fontsource/montserrat/500.css"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="@fontsource/montserrat/700.css"
          crossOrigin=""
        />
</Head>
```

**Comment by teauxfu** [comment]
I just recently picked up Next and I haven't tried using it with Fontsource yet, but I would like to know how to do what you're trying.

So far with Next I've just run this
```js
// global styles can only be loaded here in _app.js
import "../styles/global.scss";

// this is the top level component
export default function App({ Component, pageProps }) {
  return <Component {...pageProps} />;
}
```
```scss
//global.scss
@use "../../public/fonts/iosevka-aile/iosevka-aile.css";
```

I hope this helps. If not, I'd like to help you get it working so I can do the same soon 😛

https://nextjs.org/learn/basics/assets-metadata-css/global-styles

**Comment by MuriloDutra** [comment]
@teauxfu unfortunately, this is not what I'm looking for. I want to prefetch the css files

**Comment by teauxfu** [comment]
Okay I think I have a better idea of what you're getting at now. I was overly optimistic in hoping just a css import would accomplish that, but maybe I was thinking in the right direction. 

I found a couple relevant SO posts, you may have already found these but I checked out these pages

https://stackoverflow.com/q/63023946/13090245
https://stackoverflow.com/q/64859382/13090245
https://stackoverflow.com/q/61909298/13090245

also the next docs, which don't really mention preloading at all
https://nextjs.org/docs/basic-features/font-optimization
https://nextjs.org/docs/basic-features/static-file-serving
https://nextjs.org/docs/advanced-features/custom-app

they mention that next does some font optimization (presumably including preloading?), but seems to cater to Google/Typekit webfonts

my understanding here isn't complete, but it seems like serving static + loading the css globally is the best you can do right now without having a dedicated CDN/server for your font files. it seems importing assets from `node_modules` where Fontsource keeps them works fine, but the issue I seem to be hitting is that the href passed to the link is invalid after the build step.

Outside of just manually copying the contents of `@fontsource/montserrat` into the `public` folder, I'm not sure what other options are available right now.

As an aside I'm curious about motivations for preloading the css and/or/vs preloading the woff2 files themselves. Like I mentioned, I'm new to this area. Have you measured that the font loading induces a significant delay?

**Comment by teauxfu** [comment]
possible duplicate of #83 -- see https://github.com/fontsource/fontsource/issues/83#issuecomment-957853384

probably need to tweak next.config and/or use a plugin to catch the woff2 files, but this seems a good route

**Comment by ayuhito** [comment]
I'll close this in favour of #83 since similar concerns with Next.js have been expressed there. Thanks!
