### ISSUE TITLE
Noto Sans does not render backticks correctly

### ISSUE THREAD

**Issue by hejhi** [DecliningLotus/fontsource#404]
**Describe the bug**
As described [here](https://github.com/googlefonts/noto-fonts/issues/736) and [here](https://news.ycombinator.com/item?id=12655054), there's an issue with Noto Sans and backticks—it's hard to describe, but backticks display and take up space inconsistently, and sometimes display as character accents.

**To Reproduce**
An example linked to from the aforementioned ticket:
https://jsbin.com/qizoxoc/edit?html,css,output

When entering backticks, they display and take up space inconsistently.

**Expected behavior**
Backticks should work as expected.

**Screenshot**
Taken from the aforementioned issue:
![image](https://user-images.githubusercontent.com/1711164/147295980-07936938-44b8-4992-ab42-184ee8ae5788.png)

**Additional context**
You can find detailed information on it [here](https://github.com/googlefonts/noto-fonts/issues/736)
...a css patch/workaround [here](https://github.com/googlefonts/noto-fonts/issues/736#issuecomment-628914669)
...and the solution on how to get the patched font [here](https://github.com/googlefonts/noto-fonts/issues/736#issuecomment-768889258)

**Comment by ayuhito** [comment]
Hi @hejhi,

Unfortunately, we don't apply manual patches to any fonts pulled from Google Fonts. Should they update the font themselves, our manual patches would be wiped, and there is a multitude of post-processing stuff and standards Google applies to fonts that go live on their servers which we won't be able to match by directly grabbing a separate source.

The solution is to get it fixed upstream in google/fonts.

Thanks for the issue!
