### ISSUE TITLE
font-weight does not seem to work when applied via CSS

### ISSUE THREAD

**Issue by getjeffnow** [DecliningLotus/fontsource#405]
**Describe the bug**
When attempting to change `font-weight` to say 100 or 500, etc, there appears to be no visible change.

**Comment by ayuhito** [comment]
@getjeffnow, the most probable cause for that is that you have not imported the specific weight for that font properly.

Please reference the second half of [this page](https://fontsource.org/docs/getting-started) in the documentation.

Alternatively, if you are handling your imports correctly, the font itself does not support those specific weights.
