### ISSUE TITLE
How to use with webpack?

### ISSUE THREAD

**Issue by sarink** [DecliningLotus/fontsource#407]
How exactly is this lib supposed to work?

The page at https://fontsource.org/docs/getting-started tells you to just add the font css import to your entrypoint, like so
```
import "@fontsource/open-sans/500.css"; // Weight 500.
import "@fontsource/open-sans/900-italic.css"; // Italic variant.
```
but obviously that is only going to tell webpack to load a css file (with what loader? it will do absolutely nothing until you configure it)

So there’s two problems:
1. You need to also insert this `@font-face` css string somewhere in the dom (or get a url to the .css file, this will depend on which webpack loader you choose)
2. Since the css loads fonts like `url(./files/...`) you need `./fonts` to be able to resolve from your webserver (so, I guess, moving the files from `node_modules/@font-face/files/the-font.woff` to `dist/files` ?)

and yet the docs for this lib just say:
> Fontsource supports a variety of import methods. It either assumes you are using a bundler, such as Webpack, to load in CSS

... _does it?_

I can certainly imagine how you might rig it up yourself with a combination of webpack loaders and maybe the `CopyFilesPlugin` ? Is there a corresponding special webpack plugin that can do all of this? If so, why isn't it talked about in the docs?...

**Comment by ayuhito** [comment]
Hiya @sarink,

Honestly the documentation implicitly assumes everyone is using the CSS loader and file loader for Webpack, since that's necessary for any website to build. If you have a working Webpack setup for a website, it should just work.

That, and most people nowadays probably use a framework like Next.js or Gatsby etc, which does all the basic build tool configuration for you anyways.

I don't really think it's necessary for me to include additional documentation considering how old this repository is and how no one else has really asked this question before.

Thanks for your interest! Let me know if you have any other concerns.

**Comment by sarink** [comment]
Gotcha. Honestly, I have been writing some flavor of css-in-js for so many years, I completely forgot of the css-loader's existence.

That being said, I don't see what would be so wrong with this addition:

> Fontsource supports a variety of import methods. It either assumes you are using a bundler, such as Webpack (with the css-loader), to load in CSS, or using Sass mixins which is explained here.

**Comment by ayuhito** [comment]
Webpack is a suggested bundler. But the same import method works with other bundlers like Vite or even entire different ecosystems such as Svelte (sort of). 

I'm not looking to make the documentation Webpack-centric as that is unnecessary for the rest of the crowd. Nor am I looking make individual pages for every bundler or framework out there.

If there was lots of demand for me to change the documentation, I'll be happy to accommodate. But I don't think so for this one.

**Comment by rome-user** [comment]
I am trying to use this from Webpack as well, without frameworks. My setup is a bit esoteric. I am experimenting with ClojureScript + webpack, but I have littel to not experience with Webpack or the vanilla JS ecosystem. In the past I have used Sass and separate font packages that were easy to import with Sass. I am trying to use fontsource now, but I am not sure how a minimal webpack configuration would look with fontsource.

Besides
```js
{test: /\.css$/,
 use: ["css-loader"]}
```
what more is needed? How does `file-loader` configuration look?
