### ISSUE TITLE
fonts not showing on windows machines (vite, mui, fontsource)

### ISSUE THREAD

**Issue by petertellgren** [DecliningLotus/fontsource#423]
**Describe the bug**
On windows machine when using the `import @fontsource/<FONT>` colleagues on windows machine keep getting 403 errors and no working fonts

**To Reproduce**

On a windows machine
1. clone https://github.com/petertellgren/fontsource-windows-bug.git
2. run `yarn`
3. run `yarn dev`

**Expected behavior**
see the two fonts "roboto" and "inter"

**Screenshots**
![403-error-chrome-devtools](https://user-images.githubusercontent.com/76662/152803809-af9f6be1-e1b1-48bc-aab0-6bbaa1dbf391.png)

**Comment by ayuhito** [comment]
@petertellgren, I cannot reproduce the issue with the given steps. I'm using a Windows machine on Chrome and everything seems to be loading just fine.

**Comment by petertellgren** [comment]
@DecliningLotus indeed, I today validated that it's working fine on two other machines, one running windows 10  as well as another runnning windows 11.. closing this issue as it seems isolated to a single windows 11 machine.
