### ISSUE TITLE
Montserrat - Capital 'A' not showing correctly

### ISSUE THREAD

**Issue by chrisguttandin** [DecliningLotus/fontsource#424]
**Describe the bug**
The Capitol 'A' of the Montserrat font shows some intersections similar to the ones shown here #417. 

**To Reproduce**

1. Use @fontsource/montserrat@4.5.4
2. Use the font to display an 'A'
3. The 'A' shows some intersections

**Expected behavior**
The 'A' should appear without any intersections.

**Additional context**
The bug doesn't appear when using Montserrat directly from Google Fonts.

**Comment by ayuhito** [comment]
Could you try using the variable font of Montserrat and see if the issue persists?

**Comment by chrisguttandin** [comment]
Thanks for the quick response. Using the variable font works. I just replaced `fontFace` with `fontFaceVariable`.

**Comment by johanrosenson** [comment]
@DecliningLotus v4.5.1 doesn't have this problem, but 4.5.2 and above does.

Is there any way to see what changed during versions?

**Comment by ayuhito** [comment]
@johanrosenson, looking at the commit history, it was an update from Google. No changes from Fontsource's end.
