### ISSUE TITLE
Font Request: Noto Emoji & Noto Color Emoji

### ISSUE THREAD

**Issue by CSharperMantle** [DecliningLotus/fontsource#435]
**Font Name**
* Noto Emoji
* Noto Color Emoji

**Link to font source**
https://github.com/googlefonts/noto-emoji

**Link to font license**
https://github.com/googlefonts/noto-emoji/blob/main/LICENSE

**Additional context**
Really can't figure out why all other Noto series fonts are included in Fontsource but not Noto Emoji and Co. :wink:

**Comment by ayuhito** [comment]
Should be published to NPM within the next few hours ^^
