### ISSUE TITLE
Font missing mixin for font face

### ISSUE THREAD

**Issue by christopherpickering** [DecliningLotus/fontsource#441]
**Describe the bug**
https://github.com/fontsource/fontsource/blob/main/packages/league-spartan/scss/mixins.scss
is missing the mixing for @fontface.

**Comment by ayuhito** [comment]
As stated after [FontFace Mixin Inputs](https://fontsource.org/docs/sass/mixins), `@fontFace` is only available for Google Fonts. For non-Google fonts, please use `@fontFaceCustom`.

**Comment by christopherpickering** [comment]
ops, thanks!
