### ISSUE TITLE
Repository Downsize

### ISSUE THREAD

**Issue by ayuhito** [DecliningLotus/fontsource#456]
# Repo Management

The current repository when cloned is around 8-9GB which is an insane size for a repository that shouldn't be so complex. This doesn't even include `node_modules`. The reason for that is all the font files that remain in the commit _history_. A very pointless thing since I doubt anyone has any use case for any of the older font files that remain in history. Every time a font is updated, we essentially now store both the older and newer file in the repo.

## Solution
After hopping on call with the GitHub team, we discussed that conventional solutions such as Git LFS are not appropriate since using Git as a database is not ideal. 

The current proposal I went with is to rearchitect the repository to NOT store font files. Rather, whenever a font is updated, the font files that are downloaded in CI are not committed to the repository (but all updated metadata and CSS is), but still published to NPM. It actually shouldn't be too difficult to make a change like this with no effects to end-users.

The second step has a few options because we need to do something about the existing commit history.

1. Rename this repository to legacy and start a fresh new repository with no commit history.
2. Rewrite the commit history with [BFG](https://github.com/rtyley/bfg-repo-cleaner) or [git-filter-repo](https://github.com/newren/git-filter-repo) (by deleting only the TTF/WOFF/WOFF2 files) and hope not too much gets messed up.
3. Request users to use partial clones of the repo if bandwidth is a concern.

Option 1 is the safer approach, but not ideal in terms of giving up vanity metrics such as the 2.3k star count that's been the culmination of 2 years of work that shows the support the repository has. I do think these metrics are valuable for individuals or companies to determine the trustworthiness or reliability of a project and starting from scratch is not something I'm very excited to go through with. Although, I'll get in touch with GitHub again to see if maybe those stats can be transferred over - in which case I'd be happy to go with this approach (edit - they can't 😭).

Option 2 means the history is just rewritten. Commit IDs will change, any PR references or whatnot is prone to breakage. It's messy. It's not great. But it's a solution that preserves the existing repository in some form. I don't like this, but I also don't like starting from scratch if it means giving up past stats. 

Option 3 to me sounds a bit more appealing than 2. It's not natural, but if downloading a large repo is a concern, adding instructions in the README on how to do partial clones would just be "good enough" as you won't need the history of the repository in most cases.

**Comment by alerque** [comment]
It is also possible to use a hybrid approach that uses elements from each of these. For example you could start a new repository and call it legacy, then push this repo contents there. Now you have a legacy repo for posterity but keep all the stars on this one. Then you can use git-filter-repo on a local clone to come up with a replacement repository that has all the commit history without the big blobs, then graft that history into this repository as a new branch (probably from an unfiltered root commit is possible) with a push here. At that point this repo would have two branches and you could make sure everything was co paste tic with the new one, then switch which one GitHub knows of as the default branch. Now all new cloners will be getting the lighter weight branch by default. People can be expected to migrate their local clones to the new branch. One that process seems to be well along (say in 6 months or something) you can drop the old branch from this repo — or not at your discretion.

One other thing to note is that `git` tooling is steadily getting better and dealing with partial clones. It is now possible to clone both with reduced depth (useful to people right now with the current repo state) and also with a single branch (useful in the interim hybrid above). It is also gaining features for fetching history without fetching all blobs.

I expect it will keep getting better, so you could also just do nothing and hope for the best with tooling improvements, so 3 actually has the option to get better with time while any combination of 1 and 2 with both have long term downsides.

Option №4 — of course the best option is to time travel back and warn your past self that storing all the blobs in Git was a bad idea to begin with.

**Comment by vtbassmatt** [comment]
:wave: hi there, I'm the product manager at GitHub who @DecliningLotus has been corresponding with. There's nothing secret or mysterious about what we've been discussing, so in the spirit of openness, let me share here what I shared previously in email.

I spoke with folks from GitHub teams who own watchers & stars. Moving those connections to a different repo isn't something we're able to do, for a variety of technical and policy reasons. I also looked into whether we could play games with a fork (where you fork this repo, push a new history to the new fork, and then we reparent things so that the new history is the primary repo) but that was also a dead end.

@alerque's suggestion above is an interesting one. You won't lose your stars and watchers, which is great. There may be challenges for anyone with in-flight work at the time you make the new history the default, but nothing you can't work around. In fact, if you pre-announce that you're going to do it, most people can have their work committed and merged prior to the migration date. And for others, maybe we can think of it as an opportunity to learn `git rebase` 😉 

The bigger downside is that a `git clone` still gets the whole repository over the wire, even if that history isn't reachable from the main branch. And the commits which old PRs point to will no longer appear to be the commits that introduced changes from the perspective of someone working off the main branch. (If that last sentence is confusing, let me know and I can try to illustrate... talking about Git history can be mind-bending.) This is approximately the same experience someone would have if you just push the rewritten history and don't keep the alternate branch. So in some ways, I'm not sure what keeping the alternate branch buys you except more complexity in telling people how to clone the repo.

I want to be super clear that since I'm not even a contributor to your project, I certainly don't have the full perspective on what you and your contributors need. I'm happy to share my thoughts on Git/GitHub/etc. and to help out however I can, but I wouldn't presume to make this decision for you.

**Comment by ayuhito** [comment]
Good news. The repository is much smaller with a bare clone of 8.8GB falling to 107.8MB when deleting all binary font files from the history. This is a huge 81x improvement.

Bad news. I'm a clown and I accidentally forced pushed the test repo clone into this repo. :clown_face: 
Turns out the remote origin didn't switch from this repository's URL to the test repository I had on my personal GitHub account and when I tried force pushing, it ended up here. Wow.

Damage report? Not that bad it seems.  Old closed PRs look fine and everything seems normal... except for existing PRs such as #458. I think I'll have to ask them to clone the repository again and resubmit the PR when everything here is settled down. Oops.

I haven't updated the repository code to handle not storing fonts in the repository. That's actually very easy to do since all I need to do is add all binary font file extensions to `.gitignore`, but I also accidentally deleted the binary font file fixtures for tests. No tests will pass until that's fixed. For the time being, all GitHub Action workflows are disabled. I'll fix this once I get confirmation from GitHub Support for the below issues.

Git clone seems to still return the repo with the original size but history definitely has been rewritten. I think that there may be some server side caches at play here and `git gc --prune` needs to be run server-side as suggested here: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository#fully-removing-the-data-from-github
Maybe GitHub Support can match GitLab's tools internally: https://docs.gitlab.com/ee/user/project/repository/reducing_the_repo_size_using_git.html#repository-cleanup

Updates will be posted once GitHub Support gets back to me.

**Comment by alerque** [comment]
> This is approximately the same experience someone would have if you just push the rewritten history and don't keep the alternate branch. So in some ways, I'm not sure what keeping the alternate branch buys you except more complexity in telling people how to clone the repo.

It gets you a couple things. ① A slower transition phase where less things break all at once. ② I wasn't suggesting keeping the old branch in the canonical repo long term, but only during a transition phase. Then eventually it could be removed but kept in the fork repository (now legacy). @vtbassmatt just a little secret about GitHub: you all store all forks in a single repo behind the scenes, and commit SHA links work if the data is in *any* fork. Hence the fork / rename / then rebase the original / eventually drop the legacy branch will actually not result in any dead links.

(Some of this may be moot if the current guffa isn't backed out, but it's also possible an existing fork could be re-purposed as the legacy repo to preserve links.)

**Comment by ayuhito** [comment]
Current clones now return the expected smaller size so it seems GitHub automatically swept up all the unused objects. I can already feel my editor not be sluggish from the huge Git processes running in the background. 🎉

The current tasks left to be done to finalise this issue:

- [x] Delete all existing tags 
- [x] Update gitignore to ignore the file extensions `.ttf,.otf,woff,woff2` (#461)
- [x] Figure out a solution for non-Google font submissions (#464)
- [x] Re-enable Actions Workflows
- [x] Ensure all existing PRs are migrated over to the new repo

On the last issue, existing people with clones of the repo and/or with an existing PR either need to use a **FRESH CLONE**
or if they want to preserve an existing branch they're working on, run the following Git commands:

```shell
git fetch upstream
git checkout feature
git rebase --onto upstream/main main feature
git checkout main
git reset --hard upstream/main
git push --force origin
```

This is assuming we're trying to preserve an existing branch called `feature`. Note that instead of `git fetch upstream` it could be `git fetch origin`, with all references to `upstream` replaced to `origin`.

Ideally, I'd still go with the fresh clone approach and copy things over manually just to be safe. Good thing we won't be downloading 8.8GB again!

**Comment by ayuhito** [comment]
I think all subsequent issues coming from this change are now resolved. A whopping 11 PRs which should also add a lot more redundancy to the project and prevents accidental or invalid publishes. :tada: 

3 minute builds too, which is the fastest it has been for a long time. Initial checkouts took 2-3 mins by itself before due to the large repo size, reduced to now 9 seconds.
