### ISSUE TITLE
font(bitter): missing font binaries in v4.5.4

### ISSUE THREAD

**Issue by napei** [DecliningLotus/fontsource#466]
Might be related to #456 and #465.

The font Bitter (https://fonts.google.com/specimen/Bitter) is missing the `files/` directory (and font files) in `node_modules` when installing version `4.5.4`

![image](https://user-images.githubusercontent.com/8946502/159800436-c006dc14-44c1-4ebe-b9b1-5e1ed23c52d5.png)

For comparison, the font Nunito (https://fonts.google.com/specimen/Nunito) is not missing this folder in the same version.

![image](https://user-images.githubusercontent.com/8946502/159800517-afb74e69-9abb-47c2-ae45-135b55eb4c9d.png)

End result is my app (gatsby) does not build.

![image](https://user-images.githubusercontent.com/8946502/159800583-38bf9ffe-bbb7-4848-a6dc-7c7efb5467f8.png)

This issue is not present in `4.5.3`, which contains the binaries.

**Comment by ayuhito** [comment]
Ah yes, I'm aware of the issue. It's an upstream issue of our custom publisher mass-publish. Hopefully I can get a fix for that out tonight when I'm back home.

**Comment by shensven** [comment]
+1

**Comment by ayuhito** [comment]
@napei. @shensven can you please update to the latest version and confirm this is resolved?

**Comment by shensven** [comment]
the font `@fontsource/barlow@4.5.5` is works for me, the `files/` folder is back.

**Comment by ayuhito** [comment]
Great. I only pushed out a temporary fix for now (it can happen again) but I'll work on a long term solution now that there's less pressure.

I'll close this issue upon resolution of that.
