### ISSUE TITLE
Add variable subset for Source Sans Pro

### ISSUE THREAD

**Issue by doompadee** [DecliningLotus/fontsource#476]
**Is your feature request related to a problem? Please describe.**
I want to use the variable subset of Source Sans Pro with minimal fuss, unfortunately fontsource does not provide this feature for this font.

**Describe the solution you'd like**
The Source Sans Pro font should support the variable subset just like other fonts in the repository, e.g. Open Sans. The Adobe repository provides a variable font, but lacks the weightonly variant to have a reduced file size.

**Describe alternatives you've considered**
The workaround is to perform the subsetting yourself using tools like `pyftsubset` which is a bit cumbersome. I'd much prefer to be able to use a fontsource version through npm (like I can with other fonts)

**Comment by ayuhito** [comment]
I would bring this up at [google/fonts](https://github.com/google/fonts) for them to add the variable binaries since Fontsource only mirrors Google Fonts. We can't fix this ourselves.

**Comment by doompadee** [comment]
Their feedback has been that there is a variable version of Source Sans Pro available separately: [Source Sans 3 ](https://fonts.google.com/specimen/Source+Sans+3).

Don't why this font is treated differently vs other fonts that provide different subsets under the same same, but maybe you could add it as a separate font as well.

**Comment by ayuhito** [comment]
We do have Source Sans 3 with a variable variant of it.

The reason they sometimes number it separately like this is when the font authors update a font that looks too different from before, almost like a breaking change. Google is pretty strict about not pushing large changes else we get incidents like [this](https://github.com/google/fonts/issues/1307), so they often just release an update of a font as v2 etc.

**Comment by doompadee** [comment]
Great! Thanks very much for your help. My apologies for the noise.
