### ISSUE TITLE
Font Request: IBM Plex Sans JP

### ISSUE THREAD

**Issue by ghost** [DecliningLotus/fontsource#486]
**Font Name**
IBM Plex Sans JP

**Link to font source**
https://github.com/IBM/plex

**Link to font license**
https://github.com/IBM/plex/blob/master/LICENSE.txt

**Additional context**
IBM Plex Sans (European font version) and IBM Plex Sans KR (Korean font version) are available at Google Fonts, but this Japanese font version is not available at Google Fonts. I'm sad because I'm a Japanese speaker 😥

**Comment by ayuhito** [comment]
Now available at: https://fontsource.org/fonts/ibm-plex-sans-jp
