### ISSUE TITLE
Font Request: Vazirmatn

### ISSUE THREAD

**Issue by mparvazi** [DecliningLotus/fontsource#488]
**Font Name**
Vazirmatn

**Link to font source**
https://github.com/rastikerdar/vazirmatn

**Link to font license**
https://github.com/rastikerdar/vazirmatn/blob/master/OFL.txt

**Additional context**
https://fonts.google.com/specimen/Vazirmatn

Vazirmatn is new version of Vazir:
https://github.com/fontsource/fontsource/tree/main/fonts/other/vazir

**Comment by ayuhito** [comment]
It [already exists](https://fontsource.org/fonts/vazirmatn). Rather, I think it's best for us to deprecate Vazir on our end.
