### ISSUE TITLE
Ranchers missing font files

### ISSUE THREAD

**Issue by itsmeow** [DecliningLotus/fontsource#489]
**Describe the bug**
There are no font files in the Ranchers font, making it unusable.

See: https://github.com/fontsource/fontsource/tree/main/fonts/google/ranchers/files

**Comment by itsmeow** [comment]
4.5.6 does not have this issue, only the freshly released 4.5.8.

**Comment by ayuhito** [comment]
Thanks for letting me know. I had implemented checks to prevent this in CI... however, I completely overlooked this if I was publishing new packages (to recover from a failed CI build) from a local machine. 

New packages with font files should be published within 15 minutes.

**Comment by ayuhito** [comment]
Should be resolved now. Thanks!
