### ISSUE TITLE
Update color-adjust to print-color-adjust

### ISSUE THREAD

**Issue by vhscom** [DecliningLotus/fontsource#491]
**Is your feature request related to a problem? Please describe.**
PostCSS is throwing a warning on fonts utilizing the `color-adjust` shorthand.

**Describe the solution you'd like**
Update to use recommended `print-color-adjust` shorthand if and when it makes sense.

**Describe alternatives you've considered**
Do nothing. It's only a deprecation warning.

**Additional context**

<img width="1680" alt="Screen Shot 2022-05-04 at 12 34 46 AM" src="https://user-images.githubusercontent.com/97140109/166498703-7a763005-8e60-48da-bf9a-a9d65919ad99.png">

https://github.com/postcss/autoprefixer/issues/1454

**Comment by ayuhito** [comment]
I don't think this has anything to do with Fontsource considering I've never heard about this CSS property, much less be able to code it in.

[This](https://github.com/fontsource/fontsource/blob/main/fonts/google/inter/index.css) is the CSS that you are loading when importing it.

**Comment by vhscom** [comment]
Right you are. The error message is pointing at the wrong thing. Looks like this issue is within Tailwind. Sorry for the noise!
