### ISSUE TITLE
[Feature Request] Argument for `fontFaceCustom` mixin to exclude `woff`

### ISSUE THREAD

**Issue by lonix1** [DecliningLotus/fontsource#492]
**Is your feature request related to a problem? Please describe.**
I use webpack. I do this:
````scss
@import '~@fontsource/roboto/scss/mixins.scss';
@include fontFaceCustom();
````

That gives us `woff` and `woff2`. The `fontFaceCustom` mixin doesn't have a way to disable `woff`.

**Describe the solution you'd like**
It would be nice to have another [mixin argument](https://github.com/fontsource/fontsource/blob/19a0c644c320033d3b5730e9dd2a9eb4739e4b44/fonts/google/open-sans/scss/mixins.scss#L35) that allows us to exclude `woff`.

**Describe alternatives you've considered**
Living with it

**Additional context**
no

Thank you!

**Comment by thasmo** [comment]
@lonix1, what's the reason to have `woff` files excluded?

(Also, nowadays probably all [relevant browsers support `woff2`](https://caniuse.com/?search=woff2), so removing support for `woff` in general could be an option too.)

**Comment by lonix1** [comment]
@thasmo Because woff is much larger. And it's hardly used at all. It's dead weight.

Another argument to that mixin would allow us to exclude it. And it would be backward compatible for those who still want woff.

**Comment by ayuhito** [comment]
> (Also, nowadays probably all [relevant browsers support `woff2`](https://caniuse.com/?search=woff2), so removing support for `woff` in general could be an option too.)

I don't think that's an option as we still see a decent amount of usage for it. Although not easily traceable, one metric indicating high woff usage is through this [CDN](https://www.jsdelivr.com/package/npm/@fontsource/roboto).

**Comment by thasmo** [comment]
If the reason, for excluding `woff` files from the `src` property, is the file size, that wouldn't be a problem because browsers pick the first supported format anyway. `woff` only gets loaded if the client does not support `woff2`, so defining `woff` after `woff2` in the `src` property of the `@font-face` declaration shouldn't be an issue related to file/transfer size.

**Comment by ayuhito** [comment]
I do feel that offering developer flexibility is more favourable than restricting them if we don't know the various use cases.

In the case of websites, I wouldn't recommend it, as explained above.

But a case I can think of is maybe an Electron app where bundling the woff file would actually be deadweight and affect final export size.

**Comment by lonix1** [comment]
Yes in apps or wasm apps they add no value. And it just adds friction to our build pipeline for no reason.

I don't ask that it be removed, just that an arg is available to exclude it. The same way we don't include `ttf`, `eot` anymore.

**Comment by ayuhito** [comment]
We've rewritten the Sass integration entirely for [v5](https://fontsource.org/docs/getting-started/migrate-v5) 🎉 The new `$formats` prop should let you select this. Please let us know if you run into any issues!
