### ISSUE TITLE
Poppins Font Not Working

### ISSUE THREAD

**Issue by renchris** [DecliningLotus/fontsource#495]
**Describe the bug**
I working on a React, TypeScript, Chakra UI project.

I am using two fonts: DM Sans (for heading text) and Poppins (for body text). I have followed the instructions on the Font Preview to download via Yarn. DM Sans displays and renders properly, but Poppin does not.

**To Reproduce**

1. Go to 'https://fontsource.org/fonts/poppins'
2. Follow instructions to download by running in the terminal in the project directory: "yarn add @fontsource/poppins"
3. Add fonts to the theme typescript file
```
import { extendTheme } from '@chakra-ui/react'
import { createBreakpoints } from '@chakra-ui/theme-tools'
import components from './components'

const fonts = {
  heading: 'DM Sans, sans-serif',
  body: '\'Poppins\', sans-serif',
}

const theme = extendTheme({
...,
  fonts
})

export default theme
```

6. See font not rendering (only the san-serif fallback)
Result
![image](https://user-images.githubusercontent.com/57972348/168738471-eec97271-d752-417f-807a-01eb6821c6c3.png)
Expected
![image](https://user-images.githubusercontent.com/57972348/168738570-da257572-a5a4-41cf-826f-a9cb60494177.png)

**Expected behavior**
I expect that the Poppin font should be rendering properly. See above for results and expected

**Screenshots**
See screenshots above

**Additional context**
Again, DM Sans works but Poppins does not

**Comment by ayuhito** [comment]
Try this for the fonts styling: 
```
const fonts = {
  heading: 'DM Sans', sans-serif,
  body: 'Poppins', sans-serif,
}
```

Stuff like sans-serif shouldn't be enclosed in quotes, and I wasn't sure what was going on with the backslashes for Poppins.

**Comment by jwr1** [comment]
@ayuhito, the whole string needs to be quoted, since its in javascript, in addition to the family names with white-space.

@renchris, from your example, you didn't mention importing the fonts. If you didn't import them, a correct example would be:
```js
import { extendTheme } from '@chakra-ui/react'
import { createBreakpoints } from '@chakra-ui/theme-tools'
import '@fontsource/poppins'
import '@fontsource/dm-sans'
import components from './components'

const fonts = {
  heading: '\'DM Sans\', sans-serif',
  body: 'Poppins, sans-serif',
}
```

**Comment by ayuhito** [comment]
Oh, right. Totally forgot we're writing JS, you're totally right on that. Out of personal preference, however, I'm not a big fan of using backslashes to escape the quotation markers. Would just wrap it using backticks or double quotes like we do on the [Fontsource website](https://github.com/fontsource/fontsource/blob/main/website/src/theme.tsx#L22).

**Comment by renchris** [comment]
Hi. Thanks @ayuhito and @jwr12135 for contributing to the ticket quickly.

You're right, I needed to add to my theme file:
`import '@fontsource/poppins'
import '@fontsource/dm-sans'`
I have re-upped the front-end and the Poppins font is displayed correctly. I'm curious to why DM Sans went through okay without the import.

My TypeScript ESLint suggests to use the backslashes.
I get an error of:
 `Strings must use singlequote.eslint[@typescript-eslint/quotes](https://typescript-eslint.io/rules/quotes)`
with the quick fix turning into usage of the backslashes:
`const fonts = {
  heading: '\'DM Sans\', sans-serif',
  body: '\'Poppins\', sans-serif',
}`
I suppose I could disable or change the rule and settings being up to the preference of style.

**Comment by jwr1** [comment]
@renchris, it's likely DM Sans is already installed on your device. When you tried to use the font, it was able to find the local version on your computer.

**Comment by ayuhito** [comment]
I just realised this confusion stems from the Chakra UI docs which incorrectly reference the local variants of the fonts, so it's probably best for me to make a PR there to correct that.
