### ISSUE TITLE
Font Request: Material Symbols

### ISSUE THREAD

**Issue by curtvict** [DecliningLotus/fontsource#497]
**Font Name**

Material Symbols

**Link to font source**

https://developers.google.com/fonts/docs/material_symbols

**Link to font license**

https://developers.google.com/fonts/docs/material_symbols#licensing

**Additional context**

Being able to import these variable icon fonts directly from fontsource would be very convenient! To be clear, these are the newest iteration of the MUI icons, not those that are already packaged with fontsource.

**Comment by Eliawyn** [comment]
You can find the Google icons font here: https://github.com/fontsource/fontsource/tree/main/fonts/icons/material-icons
And other versions of the Google icons in the parent folder: https://github.com/fontsource/fontsource/tree/main/fonts/icons

**Comment by curtvict** [comment]
@ayuhito I took a stab at implementing this but wasn't able to get very far. I was curious what you thought about this feature request? Google has completely replaced its icons with Material Symbols on their site https://fonts.google.com/icons

**Comment by ayuhito** [comment]
I don't have an issue adding this. I just don't have enough time these days and for the rare days where I do have time, I'm addressing the more problematic issues on the repo.

What issues did you run into? I'm happy to guide you.

**Comment by curtvict** [comment]
Thanks for the response @ayuhito. I'll give this another run on Thursday this week and report back with any hiccups I run into.

**Comment by vhscom** [comment]
Are the symbols (or lack thereof) the reason things like `<i class="material-icons">wallet</i>` are not resolving with the current material ui included with Material Icons delivered by Fontsource? What's the easiest way for users to know which icons are available versus what's not as what Fontsource and Google offers further diverge?

**Comment by ayuhito** [comment]
> Are the symbols (or lack thereof) the reason things like `<i class="material-icons">wallet</i>` are not resolving with the current material ui included with Material Icons delivered by Fontsource? What's the easiest way for users to know which icons are available versus what's not as what Fontsource and Google offers further diverge?

Currently, icons are manually updated, which isn't ideal. However, it is automatable so the versions remain up to date.  I'm focused elsewhere but it would be possible to add an `icons.json` dataset in [google-font-metadata](https://github.com/fontsource/google-font-metadata) which Fontsource can then pick up in its normal build cycles if anyone wants to contribute that.

**Comment by ayuhito** [comment]
Coming in V5 (fontsource/google-font-metadata#124) 👀

**Comment by ayuhito** [comment]
Released in V5. 🎉 You can check out the documentation for it [here](https://fontsource.org/docs/getting-started/material-symbols).

**Comment by curtvict** [comment]
Just implemented in my project. Many thanks @ayuhito! It's working great!

**Comment by peterhirn** [comment]
Thanks a lot for adding this. We're using `@fontsource/material-symbols-outlined` in our project which made testing different icons incredible easy. 💯

If I understand correctly I need to switch to variable fonts when I want to use filled icons? The reason I'm asking is that the variable fonts are quite a bit larger and I don't really want to force my users to download another 500k just for a couple icons.

For now I'm just going to add the filled icons I need as raw `svg`. Do you guys have a better approach or suggestions? (besides immutable caching obviously)

**Comment by ayuhito** [comment]
> For now I'm just going to add the filled icons I need as raw `svg`. Do you guys have a better approach or suggestions? (besides immutable caching obviously)

Using SVGs to individually pick out the necessary icons will always lead to smaller bundles, especially if it's only a couple of icons. I think using font files only makes sense if you're using a LOT of icons and it's usually more for developer convenience than anything else. I personally don't advocate using icons as a font and always import individual SVGs (especially when you optimise the SVGs on top of that), but there are niche use cases where it makes sense.
