### ISSUE TITLE
Font Request: Add font-style bold to montserrat

### ISSUE THREAD

**Issue by amandachagas** [DecliningLotus/fontsource#498]
**Font Name**
Montserrat

**Link to font source**
https://fonts.google.com/specimen/Montserrat#standard-styles

**Link to font license**
Accepted licenses are SIL OFL, Apache 2, MIT and Ubuntu Font License 1.0.

**Additional context**
Hi there! I noticed that even setting the installed Montserrat font to font-weight: 800; it would not bold the text. Then I realized the bold style for Montserrat is not included! There is only [italic,normal]. Could you please make this enhancement to the project?

**Comment by ayuhito** [comment]
Hiya, `font-weight: 800;` already exists in the package. `bold` is not a `font-style`. It's synonymous to 800 for `font-weight`.

Are you sure you're importing the right CSS?
