### ISSUE TITLE
Feature request dynamic subset generic script

### ISSUE THREAD

**Issue by myodan** [DecliningLotus/fontsource#500]
**Is your feature request related to a problem? Please describe.**
I've tried adding a "dynamic subset" to Pretendard fonts from FontSource, but I don't know how.

**Describe the solution you'd like**
I would like to add a method or function to add dynamic subset.

**Describe alternatives you've considered**
It would be nice to be able to add dynamic subsets just like using generic script now.

**Comment by ayuhito** [comment]
I'll close this in favour of #501 which suggests auto subsetting. Thanks!
