### ISSUE TITLE
"Tarball has too many files" Error when trying to get package metadata

### ISSUE THREAD

**Issue by elektromodulator** [DecliningLotus/fontsource#502]
Hi,

When I try to get the package metadata for @fontsource/roboto-mono package from npmjs.org's REST API (we check the popularity in out CI build pipelines), I get the following error:

WARNING: @fontsource/roboto-mono : API returned error for https://api.npms.io/v2/package/%40fontsource%2froboto-mono : Tarball has too many files

Can you fix this issue?

**Comment by ayuhito** [comment]
We can't reduce the file count in the package without breaking it. This is a problem with NPM, not us.
