### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by yepMad** [DecliningLotus/fontsource#503]
**Describe the bug**
After building the project and putting it online, there is a warning on the console that says there was an error decoding the downloaded fonts. I use Rubik.

**To Reproduce**

1. Create project with CRA typescript template
2. Install and use @fontsource/rubik
3. Build the project
4. Open the console

**Expected behavior**
No warnings will be generated.

**Screenshots**
![image](https://user-images.githubusercontent.com/22564368/171570950-eb4311a0-a4e2-4670-bb38-74902d37ce41.png)

**Additional context**
```
    "@chakra-ui/react": "^2.0.0-next.5",
    "@craco/craco": "^6.4.3",
    "@emotion/react": "^11",
    "@emotion/styled": "^11",
    "@fontsource/rubik": "^4.5.9",
    "@hookform/resolvers": "^2.8.8",
    "@reduxjs/toolkit": "^1.8.1",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^13.0.0",
    "@testing-library/user-event": "^13.2.1",
    "@types/jest": "^27.0.1",
    "@types/node": "^16.7.13",
    "@types/react": "^18.0.0",
    "@types/react-dom": "^18.0.0",
    "apexcharts": "^3.35.2",
    "axios": "^0.27.2",
    "framer-motion": "^6",
    "i18n-js": "^3.9.2",
    "query-string": "^7.1.1",
    "react": "^18.1.0",
    "react-apexcharts": "^1.4.0",
    "react-dom": "^18.1.0",
    "react-hook-form": "^7.31.1",
    "react-icons": "^4.3.1",
    "react-query": "^3.39.0",
    "react-redux": "^8.0.1",
    "react-router-dom": "^6.3.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.4.2",
    "web-vitals": "^2.1.0",
    "yup": "^0.32.11"
```

**Comment by ayuhito** [comment]
Seems to be a Webpack configuration error in CRA/craco when they migrated from css-loader v5 to v6.

Please refer to the solutions mentioned in webpack-contrib/css-loader#1354.
