### ISSUE TITLE
Nunito Sans latin-ext imports wrong font

### ISSUE THREAD

**Issue by fila90** [DecliningLotus/fontsource#511]
**Describe the bug**
Importing any of `latin-ext` fonts imports some fonts that are not of `nunito-sans` family 

**To Reproduce**

`import '@fontsource/nunito-sans/latin-ext.css';`

**Expected behavior**
To imports correct font family.
For example `import '@fontsource/nunito-sans/latin.css';` works as expected 

**Screenshots**
Completely wrong font family 
![Wrong fonts](https://user-images.githubusercontent.com/16494464/176413604-8c862519-fcd6-4800-b0fa-b0bff2ce99ea.png)

Correct latin font
![Correct fonts](https://user-images.githubusercontent.com/16494464/176413628-70ed0deb-63f4-4126-9834-f0d432119089.png)

**Comment by jwr1** [comment]
latin-ext fonts use [this character set (Latin Extended-A)](https://en.wikipedia.org/wiki/Latin_Extended-A). The latin-ext fonts were meant to be used along with the latin fonts, so you can use both Latin characters (like a,h,q,x) and Latin extended characters (ā,ć,ĝ,Ŋ). The only case you would use latin-ext without latin is if your only using those extended characters, which is very unlikely. It's possible the font that is showing up in your preview is just a fallback when the font does not have those preview characters. Try using nunito-sans latin-ext with a Latin Extended character.

**Comment by fila90** [comment]
> latin-ext fonts use [this character set (Latin Extended-A)](https://en.wikipedia.org/wiki/Latin_Extended-A). The latin-ext fonts were meant to be used along with the latin fonts, so you can use both Latin characters (like a,h,q,x) and Latin extended characters (ā,ć,ĝ,Ŋ). The only case you would use latin-ext without latin is if your only using those extended characters, which is very unlikely. It's possible the font that is showing up in your preview is just a fallback when the font does not have those preview characters. Try using nunito-sans latin-ext with a Latin Extended character.

That explains a lot

If I use it like this

```js
import '@fontsource/nunito-sans/latin.css';
import '@fontsource/nunito-sans/latin-ext.css';
```

it works as expected.
