### ISSUE TITLE
Font weight missing in IBM Plex Sans

### ISSUE THREAD

**Issue by qtn-g** [DecliningLotus/fontsource#514]
**Describe the bug**
Only font weight 100, 600 are available.

**To Reproduce**
install font `yarn add @fontsource/ibm-plex-sans`

**Expected behavior**
Expect to have 100, 200, 300, 400, 500, 600 and 700 as mentioned in the [documentation](https://github.com/fontsource/fontsource/tree/main/fonts/google/ibm-plex-sans#readme)

**Additional context**
I'm using NextJS 12.2 with Chakra-ui 2.2.3

**Comment by ayuhito** [comment]
Could you clarify how you're loading up these fonts? I don't think it's on our end as all files seem to be available according to: https://www.jsdelivr.com/package/npm/@fontsource/ibm-plex-sans?path=files

**Comment by qtn-g** [comment]
Sorry for the delay !

Like Chakra-UI provide https://chakra-ui.com/community/recipes/using-fonts

```
import '@fontsource/ibm-plex-sans'
import '@fontsource/ibm-plex-mono'

export default {
  fonts: {
    heading: 'IBM Plex Sans, sans-serif',
    body: 'IBM Plex Sans, sans-serif',
    mono: 'IBM Plex Sans, monospace',
  },
}
```

**Comment by ayuhito** [comment]
@quentingirard, you need to specify the weights you are importing as shown [here](https://fontsource.org/docs/getting-started).
