### ISSUE TITLE
Font Request: Albert Sans

### ISSUE THREAD

**Issue by waylonrobert** [DecliningLotus/fontsource#529]
**Font Name**
Albert Sans

**Link to font source**
https://github.com/usted/Albert-Sans

**Link to font license**
https://fonts.google.com/specimen/Albert+Sans#license

**Additional context**
Albert Sans is in the repo (https://github.com/fontsource/fontsource/tree/main/fonts/google/albert-sans), but it's missing an NPM package and shows a 404 on the website.

**Comment by ayuhito** [comment]
Related to #513. Should have a fix out this week.
