### ISSUE TITLE
@fontsource/league-gothic@4.5.2 is empty 

### ISSUE THREAD

**Issue by Ozerich** [DecliningLotus/fontsource#541]
**Describe the bug**

After install last version (**4.5.2**) of "**League Gothic**" font the folder _./node_modules/@fontsource/league-gothic_ contains only package.json file. There is no css files

After install **4.5.1** this folder is not empty and contains all valid css files.

Run
`yarn add @fontsource/league-gothic`

Check
`./node_modules/@fontsource/league-gothic`

**Expected behavior**
Folder contains css files

**Screenshots**
<img width="231" alt="image" src="https://user-images.githubusercontent.com/406041/183478247-b26e7c11-5462-42d2-9e53-1440004378b7.png">

**Comment by ayuhito** [comment]
I've pushed a fix but it'll take around an hour to rebuild the whole repo to check if there are no issues and publish. Thanks for letting me know!

https://github.com/fontsource/fontsource/actions/runs/2820092870

**Comment by Ozerich** [comment]
It looks good now, thank you
