### ISSUE TITLE
Add Droid Serif

### ISSUE THREAD

**Issue by X-Equals-Zero** [DecliningLotus/fontsource#559]
**Describe the bug**

The font found at https://www.npmjs.com/package/typeface-droid-serif
suggests replacing 'typeface-droid-serif' with 'fontsource-droid-serif' but this font does not exist in this package.

**To Reproduce**

N/A

**Expected behavior**
Fontsource to contain Droid Serif.

**Comment by ayuhito** [comment]
You may be looking for [Noto Serif](https://github.com/google/fonts/issues/4469) instead. Is that an acceptable compromise?

Otherwise, someone will need to PR to manually add this as it's no longer listed on Google.

**Comment by X-Equals-Zero** [comment]
> 

Thanks, this is perfect!
