### ISSUE TITLE
Fontlist JSON as a package

### ISSUE THREAD

**Issue by kof** [DecliningLotus/fontsource#564]
**Is your feature request related to a problem? Please describe.**

I need to render the list of fonts we support from fontlist.json.

**Describe the solution you'd like**

It would be nicer to get this file by installing a package rather than fetching it using github's API.
I can see you could use such a package too instead [here](https://github.com/fontsource/fontsource/blob/main/api/src/fontlist/services/fontlist.service.ts#L44)

**Comment by ayuhito** [comment]
I don't think we'll support this as there are multiple ways to fetch `FONTLIST.json`. I don't want to add more complexity with a package.

[Fontsource API](https://api.fontsource.org/fontlist)

[jsDelivr CDN](https://cdn.jsdelivr.net/gh/fontsource/fontsource@main/FONTLIST.json)

I'd recommend the CDN option as it is way more performant and reliable.
