### ISSUE TITLE
Open Sans: wrong font in latin-ext woff2 file

### ISSUE THREAD

**Issue by dakur** [DecliningLotus/fontsource#565]
**Describe the bug**
Open Sans WOFF2 files for latin-ext contain wrong font.

**To Reproduce**

1. Install `@fontsource/open-sans`
1. Open `node_modules/@fontsource/open-sans/files` in your file explorer
1. Compare e.g. `open-sans-latin-ext-300-italic.woff` and `open-sans-latin-ext-300-italic.woff2` in some font viewer

**Expected behavior**
WOFF and WOFF2 files should contain the same font.

**Screenshots**

from [fontsee](https://fontsee.com/)

|woff|woff2|
|---|---|
|![image](https://user-images.githubusercontent.com/9862581/188888869-7083f519-827e-448a-ba70-8260b1cebbed.png)|![image](https://user-images.githubusercontent.com/9862581/188888932-010d0742-c2c1-460e-bda0-04419d5d08a6.png)|

**Additional context**
Maybe also some other files may be affected, I think cyrillic of cyrillic-ext have been different as well.

**Comment by ayuhito** [comment]
It's an issue with `WOFF` actually, having more glyphs than it should (but that's an upstream Google thing). Athough I'm considering deprecating subset-specific `WOFF` files in favour of the `all` subset format to reduce complexity.

You need to load both `latin` and `latin-ext` variants to get the full range of glyphs. Example - https://cdn.jsdelivr.net/npm/@fontsource/open-sans@4.5.11/400.css

**Comment by dakur** [comment]
Thanks for explanation.

> You need to load both latin and latin-ext variants to get the full range of glyphs. Example - https://cdn.jsdelivr.net/npm/@fontsource/open-sans@4.5.11/400.css

Oh yes, you're right, thanks! I don't know why I missed it. It had to be both in webpack-google-fonts-plugin as well which I'm migrating away from.

Should this issue be closed now or you want to keep it open?

**Comment by ayuhito** [comment]
Nope. I'm tracking the WOFF subset deprecation in #547. Thanks!
