### ISSUE TITLE
Support for setting `font-variant-ligature` or default values when applicable

### ISSUE THREAD

**Issue by ispringle** [DecliningLotus/fontsource#567]
**Is your feature request related to a problem? Please describe.**
Some monospace fonts use the "fi" ligature (possibly others too) and these ligatures break monospacing because they're not two char wide. You can see an example of this issue here:
https://github.com/notofonts/latin-greek-cyrillic/issues/329

**Describe the solution you'd like**
Ultimately, the solution is up to the font maintainers, but the issue can be resolved via CSS for fonts that keep the ligature around or don't make it two chars wide. To solve the issue we need to be able to set the `font-variant-ligature` to `none`. 

**Describe alternatives you've considered**
Since there is probably no reason that someone expects a monospace font to behave this way, you could just set this value in the monospace fonts that need it set, though that would require a lot of leg work and eyeballing to get done since not all fonts are doing this.

**Additional context**
VT323 does this and is how I stumbled upon this problem initially.

**Comment by ayuhito** [comment]
I don't think we need to do anything? To change the ligatures, you can set it with your own [CSS class](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures#examples). It doesn't need any modification to the `@font-face` rules we set. Or am I missing something here?

**Comment by ispringle** [comment]
True enough, but adding it to the font-face is a one-and-done solution. Say you're using an accent font that goes on... headings, the logo, maybe certain other elements. Everyone of those will now have to get a `font-variant-ligature`. It's much more expedient to just update the font-face for the broken font than it is to update ever element that will use that font. Keeps all the changes in a single place. If I one day switch the font, I'd rather update one font-face than N elements.

Can't update the body/html/:root since this will disable all ligatures for all fonts and we only want to disable, in this case, on monospace fonts.

**Comment by ayuhito** [comment]
I'd be interested in seeing what Google Fonts says on this if you make an issue relating to this topic on their repo. I don't think their API modifies `@font-face` rules for these variants and I'd rather not diverge from what their API sends out.

To me, manually tracking which monospace fonts might experience this is a big no no. If it can be automatically tracked (e.g. if Google implements this), it's more feasible since I aim to make this repository as self-sufficient as it can be for whenever I am busy.

**Comment by ayuhito** [comment]
I'll close this as I don't see this being implemented unless Google themselves follow through with this. This is out of scope for this project. Thanks for making this issue!
