### ISSUE TITLE
Add TTF support to CLI

### ISSUE THREAD

**Issue by bartvanandel** [DecliningLotus/fontsource#570]
**Is your feature request related to a problem? Please describe.**
We're currently developing an app in React-Native, using Expo, and we need to use custom fonts (specifically, Barlow). While searching for a package that provides this font, I bumped into this excellent fontsource thing. Unfortunately, the fonts are only provided as .woff and .woff2, which is not supported on Android (see e.g. [Expo documentation](https://docs.expo.dev/guides/using-custom-fonts/#beyond-otf-and-ttf)).

**Describe the solution you'd like**
It would be very nice if you could also expose .otf (and/or ttf) fonts, which seem to be the best supported font format across all platforms.

**Describe alternatives you've considered**
Alternatives in our case would be to bundle the fonts manually (which works fine, but requires keeping an eye on updated fonts manually), or use another package, which as far as I can tell don't offer as nice as a feature set (incl. easily switching to other, similar fonts) as yours.

**Additional context**
none at this point

**Comment by ayuhito** [comment]
Would #555 be a solution for you? 

While TTF/OTF files aren't in our NPM packages (due to NPM package size restrictions), we do actually have downloads including TTF/OTF files available right now with the small download button found on the top bar of the [current website](https://fontsource.org/fonts/barlow).

**Comment by ayuhito** [comment]
Perhaps email notifications for updates could be a feature to extend #555 and be more useful to you.

**Comment by bartvanandel** [comment]
#555 would be a nice resource to have available for font downloads in general, but it would still require manual work to stay up-to-date. If npm package size is the restricting factor, maybe this package could offer an npm script to download the font in a specific format (e.g. with options for otf, ttf, woff, woff2, etc)? Then we could add a `postinstall` script to our own `package.json` file to download the fonts after the package has been installed.

**Comment by bartvanandel** [comment]
For the time being though, I'm just going to have to download the fonts by myself. Gotta move forward. But having this option in the future would be nice!

**Comment by bartvanandel** [comment]
I've added our solution to a public gist, maybe you can use some of it: https://gist.github.com/bartvanandel/19921f48ce134c393bb38bb2c8887247

**Comment by ayuhito** [comment]
Thanks! This gives me a lot more insight into how I would want to structure #562 to be beneficial to many people. I want to make most of the functionality of this project to be fully portable for teams to utilise.

**Comment by bartvanandel** [comment]
You're welcome! I do realize that our script is definitely cutting some corners, for instance, it would for sure benefit from some kind of hash match or version storage, so we can keep the number of downloads to a minimum instead of on every `npm install`, but for now this was good enough for us.

**Comment by ayuhito** [comment]
Now that V5 is released, I think we could store all the TTF files into the [`font-files`](https://github.com/fontsource/font-files) quite easily. We have all the necessary metadata to do so. 

We just need to ensure when publishing to NPM, those TTF files are just ignored, as well as find all the TTF sources for all non-google custom fonts we host.
