### ISSUE TITLE
variable-full.css is gone for Inter font

### ISSUE THREAD

**Issue by iquito** [DecliningLotus/fontsource#581]
**Describe the bug**

I include `@fontsource/inter` in my project and use `@fontsource/inter/variable-full.css` to have the fully functional variable Inter font version. When upgrading from version `4.5.12` to `4.5.13` the `variable-full.css` file seems to be completely gone, without replacement. `variable.css` is still in the repository, but as far as I can tell it does not support italic font style, only different weights.

**To Reproduce**

1. Install v4.5.13 of `@fontsource/inter`
2. Compare to v4.5.12 of `@fontsource/inter`, where `variable-full.css` still exists with the necessary fonts

**Comment by ayuhito** [comment]
Thanks for letting me know, I made an accidental breaking change here with a new update from [google-font-metadata](https://github.com/fontsource/google-font-metadata) that is more suited for the v5 release. Should get a fixed version out soon!

**Comment by iquito** [comment]
Great thanks, and thanks in general for making the font easily available, it is very useful!

**Comment by ayuhito** [comment]
I've pushed a fix and a GH Action is currently rebuilding the repository with the new update. I'll double-check if the fixes were applied successfully before publishing the packages. The process should take a couple hours.

Also, thank you so much for sponsoring me! I really appreciate it. ❤️

**Comment by ayuhito** [comment]
Reopening because it didn't work and I'll have to try again tomorrow 😭

**Comment by ayuhito** [comment]
Resolved successfully now! Just update your font to the latest version.
