### ISSUE TITLE
Broken font file "roboto-latin-ext-400-normal.woff2"

### ISSUE THREAD

**Issue by 19Gerhard85** [DecliningLotus/fontsource#584]
**Describe the bug**
It seems that the file "roboto-latin-ext-400-normal.woff2" is broken or incomplete.
Comparing "roboto-latin-ext-400-normal.woff2" with "roboto-latin-400-normal.woff2" in FontForge showing missing characters for the extended version.

**To Reproduce**
Use the roboto-latin-ext-400-normal.woff2 file.

**Expected behavior**
Showing all characters.

**Screenshots**
roboto-latin-400-normal.woff2 
![grafik](https://user-images.githubusercontent.com/1492978/195052358-2dee06d9-d6b6-4bb8-b32b-52e0f3b0b588.png)

**roboto-latin-ext-400-normal.woff2**
![grafik](https://user-images.githubusercontent.com/1492978/195052418-087f9a69-1582-45df-ba5d-e08e07cd6149.png)

**Comment by ayuhito** [comment]
That is intended behaviour. You need to import both `latin` and `latin-ext` to get both. These are files that match the `unicode-range` specified in the normal CSS files since we wouldn't want duplicate glyphs after all.
