### ISSUE TITLE
Update Khand

### ISSUE THREAD

**Issue by henriquecm** [DecliningLotus/fontsource#614]
### Describe the bug

The version on Google fonts is out of date for years.
The glyph for Í show as É.

Related Issue:
https://github.com/itfoundry/khand/issues/2

### Steps to Reproduce

1. Install the latest version
2. Import the font
3. Set the font-family for Khand
4. Type a text that contains Í.
5. It will show as É.

**Comment by ayuhito** [comment]
Looks like [this hotfix](https://github.com/google/fonts/pull/5507) that addresses it will be live quite soon which will be mirrored by Fontsource in the coming weeks.

For future reference, Fontsource will never attempt to overwrite an existing Google Font with our own variant as that brings additional maintenance burden on us and we lose parity on other features like the variable version of Khand Google is working on. All issues should be resolved upstream.
