### ISSUE TITLE
Chivo Mono not reachable from API

### ISSUE THREAD

**Issue by degobbis** [DecliningLotus/fontsource#616]
### Describe the bug

The font is offered on the site, but it is not available via the API:
https://api.fontsource.org/chivo-mono

### Steps to Reproduce

1. Click on https://fontsource.org/fonts/chivo-mono
2. Select Your preferences
3. Click on Download or call the API https://fontsource.org/fonts/chivo-mono
4. See the error message 'not found'

### Expected behavior

I expect the download package or the font JSON from the API.

### OS

Linux

### Browser

Firefox

**Comment by ayuhito** [comment]
The current API is fairly buggy and de-syncs with the website frequently as it was designed as a separate entity. It will hopefully catch up in a few days but there isn't anything I can do at the moment unfortunately.

#597 is a website built on a brand new speedy and resilient backend which will also replace the current API endpoints. This solution will be far more reliable with multiple levels of fallback. I'm aiming to get this completed within a couple of months.

**Comment by degobbis** [comment]
Thank you for pointing this out.
Will the API call and responses change?

**Comment by ayuhito** [comment]
The API endpoints and responses will remain the same. No breaking changes should occur.
