### ISSUE TITLE
Font Request: Titillium Web Variable Font

### ISSUE THREAD

**Issue by Th3S4mur41** [DecliningLotus/fontsource#618]
### Font Name

Titillium Web Variable Fonts

### Link to font source

https://github.com/eliheuer/titillium-web-vf

### Link to font license

https://github.com/eliheuer/titillium-web-vf/blob/master/OFL.txt

**Comment by ayuhito** [comment]
We can't replace existing fonts provided by Google Fonts in this repository to prevent future mismatching conflicts. This will need to be resolved upstream at: https://github.com/google/fonts/issues/3230
