### ISSUE TITLE
Can't install with pnpm

### ISSUE THREAD

**Issue by paoloricciuti** [DecliningLotus/fontsource#621]
### Describe the bug

I'm trying to install a couple of fonts with pnpm but it can seem to finish the install process.

### Steps to Reproduce

1. initialize a project with pnpm
2. try to install a font

**Comment by jwr1** [comment]
What errors are you getting in the console when you try to install?

**Comment by paoloricciuti** [comment]
Nothing it just hangs there without completing the process

**Comment by jwr1** [comment]
Try installing with `pnpm install --reporter` and see if anything useful shows up. I'm guessing this is ultimately an issue on your computer because fontsource seems to work with pnpm just fine for me. You could also try clearing the pnpm store cache incase anything is causing issues there.

**Comment by paoloricciuti** [comment]
Mmm it just started working again...really strange.
