### ISSUE TITLE
Font Request: Lato (more weights)

### ISSUE THREAD

**Issue by tomprince** [DecliningLotus/fontsource#624]
### Font Name

Lato

### Link to font source

https://www.latofonts.com/ ([Direct Download](https://www.latofonts.com/download/lato2oflweb-zip/)).

### Link to font license

[SIL Open Font License 1.1](http://scripts.sil.org/OFL) (linked from [download page](https://www.latofonts.com/lato-free-fonts/)

### Additional context

It appears that the google fonts version of the font does not include all the available weights.

The main page for the font also suggests that google fonts does not have the current version of the font, though I don't know if that statement is still accurate.

I did just report a similar issue with the corresponding google font (via https://fonts.google.com/specimen/Lato/about).

**Comment by ayuhito** [comment]
We can't manually modify any font packages from Google as they push regular updates themselves which will overwrite any changes we make. Nor am I willing to make packager changes and add additional maintenance burden to manually keep these fonts up to date. 

You'll need to wait for google/fonts#3978 to be resolved for more options instead.

Thanks for the issue!
