### ISSUE TITLE
Overpass font wrongly aligned

### ISSUE THREAD

**Issue by JosuaMeier** [DecliningLotus/fontsource#625]
### Describe the bug

The overpass font is wrongly aligned with to much space at the bottom.

With fontsource:
![Bildschirmfoto 2023-01-16 um 14 30 32](https://user-images.githubusercontent.com/9655522/212690575-6bb9c104-215a-4120-9a16-c15b33c23a7a.png)

With google cdn: 
![Bildschirmfoto 2023-01-16 um 14 33 49](https://user-images.githubusercontent.com/9655522/212690596-502aa671-690d-45c3-918d-660751ead6e7.png)

### Steps to Reproduce

1. Install font via `npm install @fontsource/overpass`
2. Add it to your app `import '@fontsource/overpass/400.css';`
3. Use it with `font-family: 'Overpass';`

### Expected behavior

Text should be vertically middle aligned.

### OS

Mac

### Browser

Chrome

**Comment by JosuaMeier** [comment]
Problem happens with version 4 of overpass font. Is there a option to use version 3.x?

**Comment by ayuhito** [comment]
Just for reference, does this happen with `import '@fontsource/overpass/variable.css';` with `font-family: 'OverpassVariable';`?

**Comment by JosuaMeier** [comment]
Yes, 

> Just for reference, does this happen with `import '@fontsource/overpass/variable.css';` with `font-family: 'OverpassVariable';`?

Yes, still happen.

**Comment by JosuaMeier** [comment]
An short update: 
It is also **not** working with google cdn (https://fonts.googleapis.com/).
Its working with other cdn like cloudflare, keycdn and font-library. 
Google is using version 4 (https://github.com/google/fonts) while the others using verison 3 (https://github.com/RedHatOfficial/Overpass).

**Comment by ayuhito** [comment]
We mirror Google Fonts and can't necessarily make changes to font packages related to them due to maintenance burden concerns. If this is a valid bug that is visible using their CDN, I think you should make an issue [in their repo](https://github.com/google/fonts) instead as it's an upstream issue.

**Comment by JosuaMeier** [comment]
@ayuhito I will try that, thanks for your help.
For anyone searching here for an answer, I opened a bug in the google fonts repo.
https://github.com/google/fonts/issues/5795
