### ISSUE TITLE
Font Feature Settings

### ISSUE THREAD

**Issue by djmtype** [DecliningLotus/fontsource#629]
### Describe the feature you'd like to request

If there is a way to add `font-feature-settings` I haven't been able to find it on the documentation site. 
### Describe the solution you'd like

Provide an additional stylesheet to access extended characters. 

### Additional context

Example of using `font-feature-settings` for Work Sans: 
`font-feature-settings: "ss01", "ss02", "ss04", "ss06", "case"`

**Comment by djmtype** [comment]
Looking at the code and examining the font files, it seems these characters are part of the woff files but not woff2.

**Comment by ayuhito** [comment]
This probably is related: google/fonts#1335

**Comment by ayuhito** [comment]
Please refer to #39 for future updates.
