### ISSUE TITLE
Download button error on "Fontsource" web page

### ISSUE THREAD

**Issue by Juris3D** [DecliningLotus/fontsource#630]
### Describe the bug

Clicking "download" icon for some font gives
{"statusCode":500,"message":"Internal server error"}

### Steps to Reproduce

Go to font "Gruppo" (just as example)
Click download button, one with down arrow

### Expected behavior

I expected font download, but I see {"statusCode":500,"message":"Internal server error"}

### OS

Windows

### Browser

Vivaldi

**Comment by jwr1** [comment]
It should work now. The API is a bit buggy and doesn't seem to work properly when the cache exceeds a certain limit. You can see more information about that from [this comment](https://github.com/fontsource/fontsource/issues/616#issuecomment-1362269441).
