### ISSUE TITLE
Gajraj One (from Google Fonts) is missing

### ISSUE THREAD

**Issue by YoshiWalsh** [DecliningLotus/fontsource#636]
### Describe the bug

I'm submitting this as a bug instead of a Font Request because my understanding is that all Google Fonts are meant to be supported automatically.

[Gajraj One](https://fonts.google.com/specimen/Gajraj+One) is an Open Font License font from Google Fonts which doesn't seem to be included. In the [fonts list](https://fontsource.org/fonts) it appears in the search results, but clicking it goes to a 404. There's also no package on npm for @fontsource/gajraj-one.

### Steps to Reproduce

1. Navigate to https://www.npmjs.com/package/@fontsource/gajraj-one
2. Observe that no such package exists

**Comment by ayuhito** [comment]
I'll be able to fix it in a couple days but it seems our `check-fonts` code is experiencing a Got race condition bug. Need to play around with that a little.

**Comment by YoshiWalsh** [comment]
No worries, I don't need the font urgently. I'd love to hear when it's fixed.

Thanks for your work on this project, it's very useful.

**Comment by YoshiWalsh** [comment]
Sorry to nag, I know it's not easy to maintain FOSS projects. Do you have any update on when this might be fixed?

**Comment by ayuhito** [comment]
It is technically fixed for v5, but I don't have the time to fix the current build pipeline in this repo. I'm really bogged down with a bunch of commitments (internships and looming final exams) that finishing off v5 is a slow task.

If you need the font files, feel free to pick them out from the new [v5 repo](https://github.com/fontsource/font-files). Although currently undocumented, using the new `@fontsource-utils/cli` and running `fontsource gajraj-one` should even locally build you a package!

**Comment by ayuhito** [comment]
Released at: https://fontsource.org/fonts/gajraj-one
