### ISSUE TITLE
Font-face src "non-all" woff2 file overrides "all" woff file.

### ISSUE THREAD

**Issue by mogoh** [DecliningLotus/fontsource#643]
### Describe the bug

The title is a bit chaotic, sorry for that.
I am trying my best to explain.

Some glyphs are in the `some-font-all-somthing.woff` files and not in the `some-font-something.woff2` files.
For example "☞" (U+261E : WHITE RIGHT POINTING INDEX)} is in `/fonts/google/cormorant-garamond/files/cormorant-garamond-all-400-normal.woff` but not in `/fonts/google/cormorant-garamond/files/cormorant-garamond-latin-ext-400-normal.woff2`.

The CSS files prevent "☞" being rendered.

1. U+261E is in no unicode-range.
2. `src: url('./files/cormorant-garamond-latin-400-normal.woff2') format('woff2'), url('./files/cormorant-garamond-all-400-normal.woff') format('woff');` means if the browser is capable of reading "woff2"-file, it will ignore the "woff"-file.

This for example would work:

```
/* cormorant-garamond-latin-400-normal*/
@font-face {
  font-family: 'Cormorant Garamond';
  font-style: normal;
  font-display: swap;
  font-weight: 400;
  src: url('./files/cormorant-garamond-all-400-normal.woff') format('woff');
  unicode-range: U+261E;
}
```

### Steps to Reproduce

```bash
yarn add @fontsource/cormorant-garamond
```

This does not work:

```html
<!DOCTYPE html>
<html>
<head>
<link href="./node_modules/@fontsource/cormorant-garamond/400.css" rel="stylesheet">
<style>
p { font-family: "Cormorant Garamond", serif; }
</style>
</head>
<body>
<p>☞</p>
</body>
</html>
```

This does work:

```html
<!DOCTYPE html>
<html>
<head>
<style>
@font-face {
  font-family: 'Cormorant Garamond';
  font-style: normal;
  font-display: swap;
  font-weight: 400;
  src: url('./node_modules/@fontsource/cormorant-garamond/files/cormorant-garamond-all-400-normal.woff') format('woff');
  unicode-range: U+261E;
}
p { font-family: "Cormorant Garamond", serif; }
</style>
</head>
<body>
<p>☞</p>
</body>
</html>
```

### Expected behavior

The ☞-glyph only gets rendered correctly in the second example.

### Version

 "@fontsource/cormorant-garamond": "^4.5.10"

### OS

Linux

### Browser

Firefox

**Comment by mogoh** [comment]
Might be related: https://github.com/google/fonts/issues/5935

**Comment by ayuhito** [comment]
@mogoh, I'm not sure if this issue is fully relevant anymore as we now [also subset `woff` files](https://github.com/fontsource/google-font-metadata/pull/116) removing the inconsistency.  Technically speaking, now it's up to Google to extend their subsetting ranges upstream to support these characters.

Thanks for making the issue!

**Comment by mogoh** [comment]
Thank you for your work!
