### ISSUE TITLE
Font missing: Stix Two Math

### ISSUE THREAD

**Issue by ng-hai** [DecliningLotus/fontsource#644]
### Describe the bug

The package does not include `./files` folder, so CSS could not reference to that url, causing error at build time.

### Steps to Reproduce

1. Install the package
2. View content in `node_modules/@fontsource/stix-two-math`, there is no `files` folder
3. Inside each `*.css` file, the `src` is poiting to `./files/...`

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/19520278/221514706-be9ba677-3448-42f6-9b86-b6b6ee45bbbc.png">

**Error when running development mode in Next.js**
<img width="611" alt="image" src="https://user-images.githubusercontent.com/19520278/221515343-07ae5b6a-6f5c-4fbf-8bcd-d93493c7182a.png">

### Version

4.5.2

### OS

Mac

### Browser

Safari

**Comment by ayuhito** [comment]
Related #578. Please pin the package to an older version.
