### ISSUE TITLE
Gloock (from Google Fonts) is missing

### ISSUE THREAD

**Issue by coyotte508** [DecliningLotus/fontsource#657]
### Describe the bug

https://fontsource.org/fonts/gloock

It's missing but it's listed.

it's not in NPM either

### Steps to Reproduce

1. Go to https://fontsource.org/fonts/gloock
2. See 404

**Comment by jwr1** [comment]
See this comment: https://github.com/fontsource/fontsource/issues/636#issuecomment-1474879365

**Comment by ayuhito** [comment]
You can now find it here: https://fontsource.org/fonts/gloock
