### ISSUE TITLE
Font Request: Delicious Handrawn 

### ISSUE THREAD

**Issue by dzikoysk** [DecliningLotus/fontsource#662]
### Font Name

 Delicious Handrawn 

### Link to font source

https://fonts.google.com/specimen/Delicious+Handrawn

### Link to font license

These fonts are licensed under the [Open Font License](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL): https://fonts.google.com/specimen/Delicious+Handrawn/about

**Comment by ayuhito** [comment]
You can now find it here: https://fontsource.org/fonts/delicious-handrawn
