### ISSUE TITLE
Font Request: Nunito Sans variable

### ISSUE THREAD

**Issue by tylermercer** [DecliningLotus/fontsource#669]
### Font Name

Nunito Sans (variable font)

### Link to font source

https://fonts.google.com/specimen/Nunito+Sans

### Link to font license

https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL

### Additional context

Nunito Sans was recently updated to be a variable font (see [this issue](https://github.com/google/fonts/issues/4286) in the Google Fonts repo)

**Comment by ayuhito** [comment]
https://github.com/fontsource/font-files/tree/main/fonts/variable/nunito-sans - Technically we do have this already, however, it will show up when V5 is released in a week or so.

**Comment by ayuhito** [comment]
Now available in V5 at: https://fontsource.org/fonts/nunito-sans
