### ISSUE TITLE
Montserrat Variable v5.0.0 Italic by default

### ISSUE THREAD

**Issue by Sh4rK** [DecliningLotus/fontsource#695]
### Describe the bug

I just updated to the newly-released `@fontsource-variable/montserrat`, and imported it into my CSS file with just `@import "@fontsource-variable/montserrat";`, no additional file paths at the end. I set the font to `Montserrat Variable`.

What I found when I opened my webapp is that all Montserrat fonts became Italic, regardless of me not specifying anything like that. I looked for the cause, and found that indeed the `index.css` file for the Montserrat Variable font uses the italic versions of the font: https://github.com/fontsource/font-files/blob/main/fonts/variable/montserrat/index.css

I have not checked other fonts yet, but depending on how these are created/generated, I suspect other fonts might be affected too.

### Steps to Reproduce

1. `pnpm install @fontsource-variable/montserrat`
2. In CSS: `@import "@fontsource-variable/montserrat";`
3. In CSS: `font-family: "Montserrat Variable";`
4. Open page, see italic text.

### Expected behavior

As a user, I expected the default import of a font to be regular style, but instead it was italic.

### Version

5.0.0

### OS

Windows

### Browser

Chrome

**Comment by ayuhito** [comment]
This definitely seems present [in other packages](https://github.com/fontsource/font-files/blob/main/fonts/variable/mulish/index.css) that support variable fonts. 

I think I know why. We run loops to write out every CSS file needed for the package, but writing `index.css` gets called twice. Once for normal variants... and then again for italic. Note to self, there are fonts that _only_ ship with italic fonts, so we need to default `index.css` to italic for them at least.

I'll try to get a fix for this pushed out soon!

**Comment by Sh4rK** [comment]
Thanks!
