### ISSUE TITLE
Wrong files names for fonts without defined unicode

### ISSUE THREAD

**Issue by Michsior14** [DecliningLotus/fontsource#704]
### Describe the bug

For all fonts that don't have unicode metadata defined, variant filenames are wrongly generated.
i.e. for `material-icons` currently the generated source is `~@fontsource/material-icons/files/material-icons--400-normal.woff` instead of `~@fontsource/material-icons/files/material-icons-latin-400-normal.woff`.

### Steps to Reproduce

Just include the mixin, i.e.:

```scss
@use '@fontsource/material-icons/scss/mixins' as material;

@include material.faces(); 
```

### Version

5.0.0

### Additional context

I am able to workaround this issue by adding map with empty values for subsets, i.e:

```scss
@use '@fontsource/material-icons/scss/mixins' as material;
@use 'sass:map';

@include material.faces(
  $metadata:
    map.set(
      material.$metadata,
      unicode,
      (
        latin: null,
      )
    )
);
```

**Comment by ayuhito** [comment]
Fix has been added at 34c487c96cbf9eac4ba0182c3582ca3933a8269c (accidental commit to `main` oops), but we're just going to write some more tests that snapshot the CSS outputs of the SCSS files to reduce the chances of something like this happening in a separate PR before releasing.
