### ISSUE TITLE
Investigate Changing WOFF Files When Rebuilding Repository

### ISSUE THREAD

**Issue by ayuhito** [DecliningLotus/fontsource#712]
### Description

These commits (https://github.com/fontsource/font-files/commit/de67fff8b972e3dedac930b9c34ac3f88ca59189 and https://github.com/fontsource/font-files/commit/63f05866b9b453c92938f08eece978d28aa184f3) show that when we forcefully rebuild the entire repository which includes redownloading these fonts, the binary WOFF files seem to change.

This does not seem to have an impact on end users as the font files seem valid but is non-deterministic nonetheless.

I've looked into this before, but I've not really been able to pin the issue yet.

**Comment by Sh4rK** [comment]
I think I have figured it out. I had a hunch it was some kind of race condition... and it seems like it is! My theory was that multiple files were somehow saving to the same filenames, weirdly overwriting each other, as the files are downloaded concurrently. (Might even happen without concurrency though, I'm not sure.)

So, I hacked around a bit in `packages\cli\src\google\download.ts` to collect and log various things.

First, I collected a mapping of `file name -> download URLs` in the `download` function, and got this output (I will be using ABeeZee as a demonstration):

```js
Map(4) {
  'D:/Prog/fontsource-use/fonts/google/abeezee/files/abeezee-latin-400-italic.woff' => [
    'https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCUkp8F.woff',
    'https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCUkp8FOJKuGA.woff'
  ],
  'D:/Prog/fontsource-use/fonts/google/abeezee/files/abeezee-latin-ext-400-italic.woff' => [
    'https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCUnJ8F.woff',
    'https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCUnJ8FOJKuGPLB.woff'
  ],
  'D:/Prog/fontsource-use/fonts/google/abeezee/files/abeezee-latin-400-normal.woff' => [
    'https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN2tWklg.woff',
    'https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN2tWklpUEGpA.woff'
  ],
  'D:/Prog/fontsource-use/fonts/google/abeezee/files/abeezee-latin-ext-400-normal.woff' => [
    'https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN2tuklg.woff',
    'https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN2tuklpUEGpCeGQ.woff'
  ]
}
```

(Actually I counted duplicates first, but this is more informative.)

This was gathered right before the downloads are fired off, so it clearly show that multiple files are downloaded to the same local file, thus causing the issues.

Digging a bit deeper, I also printed the metadata for ABeeZee:

- V1:

```json
{
  "family": "ABeeZee",
  "id": "abeezee",
  "subsets": [
    "latin",
    "latin-ext"
  ],
  "weights": [
    400
  ],
  "styles": [
    "italic",
    "normal"
  ],
  "variants": {
    "400": {
      "italic": {
        "latin": {
          "url": {
            "woff2": "https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCUkp8D.woff2",
            "woff": "https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCUkp8F.woff",
            "truetype": "https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCUkp8G.ttf"
          }
        },
        "latin-ext": {
          "url": {
            "woff2": "https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCUnJ8D.woff2",
            "woff": "https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCUnJ8F.woff",
            "truetype": "https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCUnJ8G.ttf"
          }
        }
      },
      "normal": {
        "latin": {
          "url": {
            "woff2": "https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN2tWkkA.woff2",
            "woff": "https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN2tWklg.woff",
            "truetype": "https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN2tWklQ.ttf"
          }
        },
        "latin-ext": {
          "url": {
            "woff2": "https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN2tukkA.woff2",
            "woff": "https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN2tuklg.woff",
            "truetype": "https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN2tuklQ.ttf"
          }
        }
      }
    }
  },
  "defSubset": "latin",
  "lastModified": "2022-09-22",
  "version": "v22",
  "category": "sans-serif"
}
```

- V2:

```json
{
  "family": "ABeeZee",
  "id": "abeezee",
  "subsets": [
    "latin",
    "latin-ext"
  ],
  "weights": [
    400
  ],
  "styles": [
    "italic",
    "normal"
  ],
  "unicodeRange": {
    "latin-ext": "U+0100-02AF,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1E00-1EFF,U+2020,U+20A0-20AB,U+20AD-20CF,U+2113,U+2C60-2C7F,U+A720-A7FF",     
    "latin": "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD"
  },
  "variants": {
    "400": {
      "italic": {
        "latin-ext": {
          "url": {
            "woff2": "https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCUnJ8DKpE.woff2",
            "woff": "https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCUnJ8FOJKuGPLB.woff",
            "truetype": "https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCklQ.ttf"
          }
        },
        "latin": {
          "url": {
            "woff2": "https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCUkp8D.woff2",
            "woff": "https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCUkp8FOJKuGA.woff",
            "truetype": "https://fonts.gstatic.com/s/abeezee/v22/esDT31xSG-6AGleN2tCklQ.ttf"
          }
        }
      },
      "normal": {
        "latin-ext": {
          "url": {
            "woff2": "https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN2tukkIcH.woff2",
            "woff": "https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN2tuklpUEGpCeGQ.woff",
            "truetype": "https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN6tI.ttf"
          }
        },
        "latin": {
          "url": {
            "woff2": "https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN2tWkkA.woff2",
            "woff": "https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN2tWklpUEGpA.woff",
            "truetype": "https://fonts.gstatic.com/s/abeezee/v22/esDR31xSG-6AGleN6tI.ttf"
          }
        }
      }
    }
  },
  "defSubset": "latin",
  "lastModified": "2022-09-22",
  "version": "v22",
  "category": "sans-serif"
}
```

We can see that the same font variants are available in both V1 and V2, and the code doesn't seem to try to limit the download to only 1 of them.

I did a comparison between the 2 versions of `abeezee-latin-400-italic.woff`, and the V2 version is smaller, and contains less data tables, but the missing ones seem to be optional, and the rest is mostly identical. One table that is very different though is the actual glyph data (`glyf`), at least in size, however I did not dig deeper into the data tables.

To be honest I don't completely understand what this V1 and V2 thing is, but it seems like we should limit the source for one font variant to only one of them.

**Comment by ayuhito** [comment]
Thank you so much for looking into this! I think I get the gist of what's happened here.

One thing that the codebase documentation is lacking is what V1 and V2 actually means. Hopefully, we can get that documented better in a future version:

#### V1

- Older CSS API - https://fonts.googleapis.com/css
- For larger fonts, there are no numbered subsets e.g. variants don't show up as `[0]` or `[1]` unlike V2.

```json
"noto-sans-jp": {
    "family": "Noto Sans JP",
    "id": "noto-sans-jp",
    "subsets": ["cyrillic", "japanese", "latin", "latin-ext", "vietnamese"],
    "weights": [100, 200, 300, 400, 500, 600, 700, 800, 900],
    "styles": ["normal"],
    "variants": {
      "100": {
        "normal": {
          "cyrillic": {
            "url": {
              "woff2": "https://fonts.gstatic.com/s/notosansjp/v51/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEi35jS0w.woff2",
              "woff": "https://fonts.gstatic.com/s/notosansjp/v51/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEi35jS1Q.woff",
              "truetype": "https://fonts.gstatic.com/s/notosansjp/v51/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEi35jS1g.ttf"
            }
          },
          "japanese": {
            "url": {
              "woff2": "https://fonts.gstatic.com/s/notosansjp/v51/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEi35TS0w.woff2",
              "woff": "https://fonts.gstatic.com/s/notosansjp/v51/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEi35TS1Q.woff",
              "truetype": "https://fonts.gstatic.com/s/notosansjp/v51/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEi35TS1g.ttf"
            }
          },
          "latin": {
            "url": {
              "woff2": "https://fonts.gstatic.com/s/notosansjp/v51/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEi35zS0w.woff2",
              "woff": "https://fonts.gstatic.com/s/notosansjp/v51/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEi35zS1Q.woff",
              "truetype": "https://fonts.gstatic.com/s/notosansjp/v51/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEi35zS1g.ttf"
            }
          },
          "latin-ext": {
            "url": {
              "woff2": "https://fonts.gstatic.com/s/notosansjp/v51/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEi35LS0w.woff2",
              "woff": "https://fonts.gstatic.com/s/notosansjp/v51/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEi35LS1Q.woff",
              "truetype": "https://fonts.gstatic.com/s/notosansjp/v51/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEi35LS1g.ttf"
            }
          },
          "vietnamese": {
            "url": {
              "woff2": "https://fonts.gstatic.com/s/notosansjp/v51/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEi35PS0w.woff2",
              "woff": "https://fonts.gstatic.com/s/notosansjp/v51/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEi35PS1Q.woff",
              "truetype": "https://fonts.gstatic.com/s/notosansjp/v51/-F6jfjtqLzI2JPCgQBnw7HFyzSD-AsregP8VFBEi35PS1g.ttf"
            }
          }
        }
      },
      ...
    }
  }
}
```

#### V2

- Newer CSS API - https://fonts.googleapis.com/css2
- Has numbered subsets for larger fonts. Defaults to the same subsets as V1 for smaller fonts.

```json
{
...
 "noto-sans-jp": {
    "family": "Noto Sans JP",
    "id": "noto-sans-jp",
    "subsets": ["japanese", "latin"],
    "weights": [100, 300, 400, 500, 700, 900],
    "styles": ["normal"],
    "unicodeRange": {
      "[0]": "U+25ee8,...,U+2f9f4",
      "[1]": "U+1f235-1f23b,...,U+25ed8",
      ...
      "[119]": "U+20,...,U+ff0e"
      },
    "variants": {
      "100": {
        "normal": {
          "[0]": {
            "url": {
              "woff2": "https://fonts.gstatic.com/s/notosansjp/v42/-F6ofjtqLzI2JPCgQBnw7HFQoggPkENvl4B0ZLgOquiXidBa3qHiDcp2RQ.0.woff2",
              "woff": "https://fonts.gstatic.com/s/notosansjp/v42/-F62fjtqLzI2JPCgQBnw7HFoxQII2lcnk-AFfrgQrvWXpdFg3KXxAMsKMbdN.0.woff",
              "opentype": "https://fonts.gstatic.com/s/notosansjp/v42/-F6ofjtqLzI2JPCgQBnw7HFQoggM.otf"
            }
          },
          ...,
        },
        ...,
      }
    }
  }
...
}
```

Reference: [google-font-metadata](https://github.com/fontsource/google-font-metadata#apiv1)

There actually used to be a bigger difference in an older version of google-font-metadata. The CSS2 API actually returns the same WOFF file for every subset. However, it's a WOFF file that contains all subsets in one big file. We used to call that the `all` subset. This was [changed when we started using a user-agent that provides subsetted WOFF files](https://github.com/fontsource/google-font-metadata/pull/116), making the difference between the two APIs smaller.

We essentially still use V1 to generate [individual subsets](https://fontsource.org/docs/getting-started/subsets) even if V2 doesn't provide them.

I think google-font-metadata has changed a lot over the years, but the URL pairs generated in [`packages/cli/src/google/download.ts`](https://github.com/fontsource/fontsource/blob/main/packages/cli/src/google/download.ts) just hasn't matched all the changes properly. It's quite a messy piece of code after all and could be improved.

### Goals

Ideally, I think we need to do the following:
- Download everything in V2.
- If and only if the font has numbered subsets, also download V1 font subsets for it.

Thankfully we no longer need to worry about the `all` subset, which makes this issue easier to resolve.

**Comment by Sh4rK** [comment]
Thanks for the explanation! To clarify, if there are numbered subsets, we want to download them also, plus the named subsets from V1 right?

Would this slightly different algorithm work?
1. Download everything in V2.
2. Download everything in V1 minus the subsets we already have from V2.

This seems a bit simpler/more general to me, as we don't need to explicitly check what kinds of subsets are available where, we just grab everything from everywhere (all at once hehe), preferring V2.

**Comment by ayuhito** [comment]
Sounds good to me!

**Comment by Sh4rK** [comment]
Ok, I'll try to implement it today.

**Comment by Sh4rK** [comment]
Some questions:

1. Regarding the `noSubset` option: it should only have any effect if V2 has only numbered subsets, right? I mean, if there are named subsets in V2, I suppose the intended behavior is to still download the V2 named subsets in that case. (And it has no effect in any other (variable, icons) cases, right?)

2. In V2, within a single font, is it possible to have both numbered and named subsets, or is it always either the one or other? (And should we assume this could change in the future?)

3. If V2 contains named subsets, are they always identical to the V1 subsets? If not, do we want only the ones from V2, or any additional ones from V1 as well? (And should we assume this could change in the future?)


The "assumption" questions are kind of hypothetical, but what I want to get at is how I should do various checks and organize the algorithm so that it can be the most future-proof. The safest would be to assume any combination of the above can happen, and decide what we should do in each case.

**Comment by ayuhito** [comment]
> 1. Regarding the `noSubset` option: it should only have any effect if V2 has only numbered subsets, right? I mean, if there are named subsets in V2, I suppose the intended behavior is to still download the V2 named subsets in that case. (And it has no effect in any other (variable, icons) cases, right?)

`noSubset` should only affect a tiny number of fonts that are immense in size, typically a CJK font. It should disable all V1 downloads. 

We want named subsets if they aren't numbered, but realistically speaking if they've been [selected to be disabled](https://github.com/fontsource/fontsource/blob/a7dcbf7fd840d158f857b06690093b80b439c5b2/packages/cli/src/google/queue.ts#L97), they most definitely are numbered [because of their large size](https://github.com/fontsource/fontsource/issues/691). Perhaps a better variable name could be `noV1Subsets` or `noNamedSubsets`. 

---

> 2. In V2, within a single font, is it possible to have both numbered and named subsets, or is it always either the one or other? (And should we assume this could change in the future?)

It is one or the other. One of the defining changes between V1 and V2 is the numbered subsets, so they shouldn't mix. Can it change? Most likely not. We used fixed [user-agents](https://github.com/fontsource/google-font-metadata/blob/main/data/user-agents.json) in google-font-metadata to get all the relevant metadata for differing file types. It shouldn't change unless Google changes something unexpectedly which I can't make any guarantees on.

A future note, Google is working on [IFT](https://w3c.github.io/IFT/Overview.html) which removes all this subset behaviour. But only newer user-agents would be able to support that once that is available so it shouldn't affect the current GFM metadata. That's a problem for the future since I have no clue how Google will implement that API-wise, but I expect to have a new set of variants to work with eventually (at which point I may deprecate V1 entirely).

---

> 3. If V2 contains named subsets, are they always identical to the V1 subsets? If not, do we want only the ones from V2, or any additional ones from V1 as well? (And should we assume this could change in the future?)

Identical. We only need V2 in that case. You mentioned this earlier:

> I did a comparison between the 2 versions of abeezee-latin-400-italic.woff, and the V2 version is smaller, and contains less data tables, but the missing ones seem to be optional, and the rest is mostly identical. One table that is very different though is the actual glyph data (glyf), at least in size, however I did not dig deeper into the data tables.

We should exclusively rely on the V2 API which probably has more optimisations done behind the scenes.
