### ISSUE TITLE
Open Sauce Sans files are empty

### ISSUE THREAD

**Issue by Sh4rK** [DecliningLotus/fontsource#717]
### Description

The `woff` and `woff2` files for the [Open Sauce Sans](https://github.com/fontsource/font-files/tree/main/fonts/other/open-sauce-sans) font are all empty / 0-sized.

Original source of the font seems to be here: https://github.com/marcologous/Open-Sauce-Fonts

**Comment by gabro** [comment]
I've opened a PR here https://github.com/fontsource/font-files/pull/30
