### ISSUE TITLE
API Rewrite

### ISSUE THREAD

**Issue by ayuhito** [DecliningLotus/fontsource#719]
### Description

The current [API](https://fontsource.org/docs/api/introduction) is slow, unreliable and quite frankly unusable for production use. I wrote it at a time when I didn't know much about APIs (I was new to programming) and how they worked.

## Changes

I'm planning on rewriting the API using Cloudflare Workers, KV and R2 to replace all the current endpoints as well as add new [variable font endpoints](https://github.com/fontsource/fontsource/issues/321) and [download endpoints](https://github.com/fontsource/fontsource/issues/555). 

I want to offload a lot of the processing done on the current website to an API since I think the functionality should be accessible to everyone. This infrastructure should also be extremely scalable and cost me very little to maintain ([sponsoring](https://github.com/sponsors/ayuhito) this project helps!).

Additionally, I think it'll be nice to have our own variant of the Google Fonts CSS API (adding stable versioned links to CSS and font files as well as other small features like SRI) which will use a CDN backed by [custom endpoints by jsDelivr](https://www.jsdelivr.com/oss-cdn) e.g. https://cdn.jsdelivr.net/fontsource/v1/font/file.woff2 etc. For example, the current website loads CSS in an inefficient way reading from an SQLite cache for each font seen on the index page and could do better from a CDN. I don't think I necessarily want to replace Google's CSS API but offer an alternative that has different guarantees.

**Comment by uuf6429** [comment]
I don't know if I should mention this here or in #724, but that issue is not fully solved - we are getting broken urls in the API response, for example, `https://api.fontsource.org/v1/fonts/roboto` yields urls like: `https://cdn.jsdelivr.net/npm/@fontsource/undefined/files/undefined-greek-100-italic.woff2`

A bit off-topic: while the current fontsource site is great UI-wise, it doesn't mention (as far as I can see) anything about terms of use, service level or even who the operators/owners are etc. This gave the impression that users can just jump in and start using it and the api without trouble or special considerations.

**Comment by ayuhito** [comment]
> I don't know if I should mention this here or in #724, but that issue is not fully solved - we are getting broken urls in the API response, for example, `https://api.fontsource.org/v1/fonts/roboto` yields urls like: `https://cdn.jsdelivr.net/npm/@fontsource/undefined/files/undefined-greek-100-italic.woff2`

I'm open to a PR to patch this because until early June I can't do much except quick reviews.

> A bit off-topic: while the current fontsource site is great UI-wise, it doesn't mention (as far as I can see) anything about terms of use, service level or even who the operators/owners are etc. This gave the impression that users can just jump in and start using it and the api without trouble or special considerations.

I made this a long time ago without much experience so a lot of this is lacking. All this is under consideration for the rewrite.

**Comment by ayuhito** [comment]
Over the next few weeks, I'll be adding proper documentation and policies regarding the API that should make it a trustworthy source for users. For now, I've implemented a barebones replacement that is far more stable and requires no infrastructure burden from our end.
