### ISSUE TITLE
API endpoints not working at all (Cloudflare error code 521)

### ISSUE THREAD

**Issue by AlexTMjugador** [DecliningLotus/fontsource#724]
### Describe the bug

`api.fontsource.org` is not working at all for me, both in GitHub Actions CI workflow Linux runners and in my local web browser. When visiting any URL belonging to `api.fontsource.org` in a web browser, such as [https://api.fontsource.org/v1/fonts?subsets=latin,latin-ext&variable=true](https://api.fontsource.org/v1/fonts?subsets=latin,latin-ext&variable=true), Cloudflare shows a 521 error code ("Web server is down"):

![Cloudflare error page](https://github.com/fontsource/fontsource/assets/7822554/4ecc8bd8-e9e9-4fdb-b450-179dabdf5280)

The problem does not appear to be a temporary fluke on the part of Cloudflare or the API host, as it has been going on for ~3 days at the time of writing.

### Steps to Reproduce

1. Send a HTTP GET request to any endpoint of the Fontsource API, preferably from a host located in Spain (judging from the lack of reports about this problem, it might be a regional CDN/DNS issue) or a GitHub Actions workflow runner hosted by GitHub (GitHub hosts these runners on Azure VMs).
2. Notice how the response signals an error.

### Expected behavior

I'm aware that the API is due for a rewrite, but its current endpoint should continue to work until that rewrite is complete, as there is currently no migration path for users.

### Version

N/A

### OS

Linux, Windows

### Browser

Firefox

### Additional context

[This issue is making my CI workflows fail](https://github.com/AlexTMjugador/Home/actions/runs/5050837584/jobs/9062028936) because they rely on downloading fonts from the Fontsource API to generate static images.

**Comment by ayuhito** [comment]
Sorry about that. It's been fixed now, but I would try to not rely on the API until #719 is resolved. The current API is very flaky and needs a lot of work.

**Comment by AlexTMjugador** [comment]
No problem! I know that the API is not as good as you want it to be, but thank you a bunch for the prompt fix to the issue :smile:
