### ISSUE TITLE
Documentation error in v5 for Inter font

### ISSUE THREAD

**Issue by iquito** [DecliningLotus/fontsource#725]
### Describe the bug

I have been using `@fontsource/inter/variable-full.css` with v4 of fontsource, and now attempted to change to v5 with the package `@fontsource-variable/inter`. The following aspects seemed confusing and incorrect to me:

1. According to the migration guide, it seems I should be able to change `import "@fontsource/inter/variable-full.css"` into `import "@fontsource-variable/inter/full.css"`, but that does not exist and it is not obvious to me how to include the right file to achieve the same with v5 as I did with v4.
2. In the `@fontsource-variable/inter` README the mentioned .css-imports do not match the actual .css files - the list is `@fontsource-variable/inter`, `@fontsource-variable/inter/wght.css` and `@fontsource-variable/inter/wght-italic.css`, yet the last one does not exist and there are other .css files (like `standard.css`) in the package instead which are not mentioned or explained.
3. The README also mentions to use the font by adding the CSS `font-family: "Inter";`, which is wrong for the variable font (should be `font-family: "Inter Variable";`), so the README in general seems to have some issues in terms of its content.

### Steps to Reproduce

Check out the README and .css files in `@fontsource-variable/inter` and compare it to the migration guide on https://fontsource.org/docs/getting-started/migrate-v5 .

### Version

5.0.1

**Comment by ayuhito** [comment]
Thanks for making an issue about the discrepancies.  To clarify, `full.css` may only exist if there are any "non-standard" axes being used. A `standard` axis can contain `opsz`, `wdth`, `slnt` and/or `wght`. Any other axes type falls into the `full` category.

The migration guide doesn't explain that nor and the variable fonts guide only lightly touches upon that topic. We can definitely improve that. Likewise, the README was poorly adjusted for the major version transition.

To highlight possible import choices, feel free to play around with the import selectors on:
- Inter: https://fontsource.org/fonts/inter/install
- Roboto Flex: https://fontsource.org/fonts/roboto-flex/install (to see how `standard` and `full` differs)

Although yes, we need to convey that better via documentation too. 👍

**Comment by iquito** [comment]
So the previous `full.css` is likely the `standard.css` now in the case of Inter? It might be good to mention a few more examples in the migration guide, and document all the possible .css-includes in a package and how to choose one, especially for variable fonts it would be good to have a "noob-friendly" explanation what you get with each choice. As a font noob I can give feedback about possible changes to the README and how understandable it is ;-)

Otherwise separating the variable fonts into their own packages seems like a really good change, thanks for the work on v5!

**Comment by ayuhito** [comment]
> So the previous full.css is likely the standard.css now in the case of Inter?

Correct, or you can use `slnt.css` since that is the only available axis, so it doesn't really matter.

> As a font noob I can give feedback about possible changes to the README and how understandable it is ;-)

I'll definitely tag you to review the documentation changes when I find the time to do so (early June) :) Although anyone else is free to take a stab at this issue if they want to in the meantime.
