### ISSUE TITLE
Inter font italic looks wrong

### ISSUE THREAD

**Issue by tayloraucoin** [DecliningLotus/fontsource#727]
### Describe the bug

When comparing the Figma version of `Inter` `font-weight 400 italic` they are noticeably different. 

Obviously the Figma version looks better, otherwise I wouldn't be making this issue. 

Can you tell which is which? (one is much more slanted than the other)

<img width="374" alt="Screen Shot 2023-05-25 at 6 24 42 PM" src="https://github.com/fontsource/fontsource/assets/10913613/70df32ea-33ad-4be9-97ce-2880d37f0413">

<img width="283" alt="Screen Shot 2023-05-25 at 6 24 25 PM" src="https://github.com/fontsource/fontsource/assets/10913613/865645d7-92e3-4627-97fa-ed072b2451cd">

### Steps to Reproduce

https://fontsource.org/fonts/inter/install

### Expected behavior

It to look like Figma.

**Comment by mbyrne00** [comment]
This is because google fonts don't define an italics version of the font: https://github.com/google/fonts/issues/2386

**Comment by ayuhito** [comment]
We mirror the Inter provided by Google Fonts. As mentioned above, this is an upstream issue.

We can't upload our own version of Inter since it would conflict with the existing version and we have a pretty strict policy to let Google eventually handle it, but perhaps releasing our own `Inter 4` could be an exception considering how long Google has been frozen on Inter. That could only be done if #728 is implemented though.

**Comment by mbyrne00** [comment]
Yea it would be great to provide a workaround if possible

**Comment by tayloraucoin** [comment]
Thanks for the info. I agree, a workaround would be great.

Perhaps however Figma is getting around this is part of the solution.

Is there any alternative way that I can access and utilize this font? Perhaps a downloadable source that I can keep locally in the repo.

**Comment by ayuhito** [comment]
> Is there any alternative way that I can access and utilize this font? Perhaps a downloadable source that I can keep locally in the repo.

You can view the official source at: https://github.com/rsms/inter

**Comment by ayuhito** [comment]
https://github.com/fontsource/font-files/issues/55 - Inter 4 has been released as part of Google Fonts.
