### ISSUE TITLE
@fontsource/cabin no longer provides variable font

### ISSUE THREAD

**Issue by ahoenerBE** [DecliningLotus/fontsource#747]
### Describe the bug

`@fontsource/cabin` 4.5.10 provides `import '@fontsource/cabin/variable.css'`.
Updating to 5.0.2 no longer has this file. The npm page has also been changed to reflect that is no longer variable, but they use the same version (v26).

### Steps to Reproduce

Install v4.5.10 and import variable css
update to 5.0.2, the file no longer exists.

### Expected behavior

As a user of the previous package, I would expect that it continues to be variable

### Version

5.0.2

**Comment by ahoenerBE** [comment]
It seems I missed the memo about fontsource-variable, please ignore

**Comment by asliwinski** [comment]
@ahoenerBE where did you find the information about this breaking change?

**Comment by ayuhito** [comment]
> @ahoenerBE where did you find the information about this breaking change?

You can find a list of all breaking changes [here](https://fontsource.org/docs/getting-started/migrate-v5)! We migrated variable fonts to a separate package under the `@fontsource-variable` scope.
