### ISSUE TITLE
asap-variable: "ital" not working

### ISSUE THREAD

**Issue by rondonjon** [DecliningLotus/fontsource#779]
### Describe the bug

I am using the latest version `5.0.6` of `@fontsource-variable/asap`.

In my code, I import and apply `@fontsource-variable/asap/standard.css?inline` (which, as I understand the README, is the version of the stylesheet that enables **all** supported axes and styles).

While changes to the `"wght" and `"wdth"` axes work as expected, it seems impossible change the style through the `"ital"` axis (0 or 1) or `font-style: italic`.

### Steps to Reproduce

This renders no italic style:

```css
font-variation-settings: 'wdth' 100, 'wght' 600, 'ital' 1;
```

| Source | Result |
| --- | --- |
| Example above | ![image](https://github.com/fontsource/fontsource/assets/8258823/7ddc82d2-7bb6-4408-84fb-cfa6da260d36) |
| Fontsource | ![image](https://github.com/fontsource/fontsource/assets/8258823/b974d337-8228-4dc0-86d0-ae45b9ffcbe7) |

This renders italic style, but in "ugly" (probably browser-generated, not as shown on the fontsource [example page](https://fontsource.org/fonts/asap)):

```css
font-variation-settings: 'wdth' 100, 'wght' 600;
font-style: italic;
```

| Source | Result |
| --- | --- |
| Example above | ![image](https://github.com/fontsource/fontsource/assets/8258823/aef2ffc7-f1ab-4fc7-8830-d46ebc627934) |
| Fontsource | ![image](https://github.com/fontsource/fontsource/assets/8258823/b974d337-8228-4dc0-86d0-ae45b9ffcbe7) |

### Expected behavior

Font should support three axes or two axes and a font-style.

### Version

5.0.6

### Browser

Chromium

**Comment by ayuhito** [comment]
Using `ital` actually needs a different CSS file - `@fontsource-variable/asap/standard-italic.css`
If you need to use both, you'd need to import both the ital and non-ital variant of the `standard` CSS file.

Feel free to check the [install page](https://fontsource.org/fonts/asap/install) to see the correct imports, although I'd love a PR that helps clarify this confusion in the docs!

**Comment by ayuhito** [comment]
I'm assuming this issue has been resolved due to no response. Thanks!
