### ISSUE TITLE
[Website] Theme preference doesn't save

### ISSUE THREAD

**Issue by itsMapleLeaf** [DecliningLotus/fontsource#787]
### Describe the bug

Loading the website always shows light theme. Even when my system is set to prefer dark, and even after toggling the theme to dark, it goes back to light on refresh or on certain navigations.

See video:

https://github.com/fontsource/fontsource/assets/19603573/28774a3b-5c26-45c5-8434-957332d74ae0

### Steps to Reproduce

1. Toggle theme from light to dark
1. Refresh

Or...

1. Toggle theme from light to dark
1. Navigate to a font page

### OS

Windows

### Browser

Edge, Firefox

**Comment by jwr1** [comment]
It works for me on Linux + Firefox. The theme preference is stored as a cookie; do you have an ad blocker or other privacy-related addon that could be restricting cookies? Though, I do agree, even without cookies, the website should be able to use the system's color scheme.

**Comment by itsMapleLeaf** [comment]
At the time, I tested this in some other browsers, including Firefox, plus under incognito / private browsing. But whatever changed since then seems to have fixed the issue! I'll mark this as resolved ✅
