### ISSUE TITLE
Fontsource font preview display page allows font substitution

### ISSUE THREAD

**Issue by boydkelly** [DecliningLotus/fontsource#793]
### Describe the bug

When searching and previewing fonts, the fontsource preview page allows font substitution.   This does not allow the user to visually see that a font does or especially doesn't support required glyphs.   Google's page however will show the expected boxes where glyphs are missing.  Note the two screen shots of the Lora font on fontsource and Google. The font substitution actually looks not bad(in this case), but this can easily lead to an inappropriate font choice.

fontsource:
![image](https://github.com/fontsource/fontsource/assets/3412972/36fe32b4-3c7f-4804-8dbc-c9130c6d3cf5)

Google:
![image](https://github.com/fontsource/fontsource/assets/3412972/6b8deb9f-2ad8-44b4-a409-e54fe2909c7d)

### Steps to Reproduce

Search for any font and type in a character that is unsupported.   For example: 

Mɔgɔkɔrɔw kaɲi ka kɛ ni ŋania ɲuman ye

Font substitution will happen.

### Expected behavior

When glyphs are missing, show missing glyphs.

**Comment by jwr1** [comment]
To fix that, we'll just need to add back in the [fallback-font](https://npm.im/fallback-font) to the preview, it should be fairly easy (we had it on the old website).
