### ISSUE TITLE
How to generate `subsets` like `fontsource` ?

### ISSUE THREAD

**Issue by scillidan** [DecliningLotus/fontsource#861]
Hi, guys~ I liked `fontsource` and I want to upload some good CJK fonts to [font-files](https://github.com/fontsource/font-files).

I read https://github.com/fontsource/font-files/blob/main/CONTRIBUTING.md and uploaded [Fusion Kai](https://fontsource.org/fonts/fusion-kai-g) fonts. But I recently found that this kind of CJK fonts are divided into many on subsets.

I referenced [this tutorial](https://markoskon.com/creating-font-subsets/) to generate `Latin subset`.  But I don't know the scope of other subsets on `fontsource`. And I found that there are some automatically generated `subset.css` files in the font folder. I know that `fontsource` used Google's APIs to generate numbered subsets from this [issue](https://github.com/fontsource/fontsource/discussions/674).

So 🤔, How do you generate subsets ?

Thanks for read :)

**Comment by ayuhito** [comment]
Hi, sorry. We don't support that yet for the custom packager 😔 

It does require #39 to be addressed with our own subsetter before #730 can be implemented. Please track those issues.

**Comment by scillidan** [comment]
OK! It also solved my problem.
