### ISSUE TITLE
Inter Variable display issue for Vietnamese

### ISSUE THREAD

**Issue by vinhphm** [DecliningLotus/fontsource#883]
### Describe the bug

Hi,

I recently updated the Fontsource's Inter Variable to version 5.0.13 and noticed there some issue with the font when displaying characters such as "ể", "ễ", "ẩ",... in Vietnamese. Tone diacritic is overlapped with vowel.  In version 5.0.12, everything looks normal and correct.

### Steps to Reproduce

1. Install Fontsource's Inter Variable 5.0.13
2. Display some Vietnamese text with characters like "ể", "ễ", "ẩ",...
3. Notice tone diacritic is overlapped with vowel.

### Expected behavior

The characters should look normal and correct as in version 5.0.12

### Version

5.0.13

### OS

Windows 11

### Browser

Chrome, Edge

### Additional context

Example:
- Version 5.0.13: https://6d557d56.vinh-dev.pages.dev/posts/migrate-from-google-domains-vi
- Version 5.0.12: https://68698be7.vinh-dev.pages.dev/posts/migrate-from-google-domains-vi

**Comment by ayuhito** [comment]
@vinhphm, can you try updating the package again to [5.0.14](https://www.npmjs.com/package/@fontsource-variable/inter)?

**Comment by vinhphm** [comment]
@ayuhito it's fixed. Thank you!
