### ISSUE TITLE
Missing icon in Material Symbols

### ISSUE THREAD

**Issue by EdoardoTona** [DecliningLotus/fontsource#884]
### Describe the bug

The icon `trophy` is not working with the material-symbols fonts (with any version: normal, variable, rounded...).

Using google font it works. I found this issue, maybe the fontsource version is not updated? https://github.com/google/material-design-icons/issues/1514

### Steps to Reproduce

```
<html>
<head>
    <link href="./node_modules/@fontsource/material-symbols-rounded/index.css" rel="stylesheet" />
    <style>
        .icon {
            font-family: 'Material Symbols Rounded';
            font-weight: normal;
            font-style: normal;
            font-size: 24px;
            display: inline-block;
            line-height: 1;
            text-transform: none;
            letter-spacing: normal;
            word-wrap: normal;
            white-space: nowrap;
            direction: ltr;
        }
    </style>
</head>
<body>
    <span class="icon">check</span>
    <span class="icon">trophy</span>
</body>
</html>
```

This code doesn't render the `trophy` icon (the `check` icon works):

<img width="194" alt="Screenshot 2023-10-30 alle 11 45 55" src="https://github.com/fontsource/fontsource/assets/12307333/0500f6ac-370e-4497-a856-9e0ca4e6291f">

### Expected behavior

Replace with the google font:

`<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded" rel="stylesheet" />`

The expected result is:

<img width="79" alt="Screenshot 2023-10-30 alle 11 47 08" src="https://github.com/fontsource/fontsource/assets/12307333/f2f0081c-6fee-42f0-abaf-c80f95ca1d36">

### Version

5.0.16

### OS

macos 14, windows 11

### Browser

safari, edge, chrome

**Comment by Asymtode712** [comment]
can i work on this issue please

**Comment by ayuhito** [comment]
> can i work on this issue please

Sure! The first thing I recommend is to check the [source metadata](https://github.com/fontsource/google-font-metadata/blob/main/data/icons-static.json) we generate via google-font-metadata. We automatically update icons with a script so if our version differs from what Google’s APIs are serving, maybe something is wrong with our script.

Edit: The latest sources are actually found in the [font-files](https://github.com/fontsource/font-files/blob/main/metadata/icons-static.json) repo since we don’t update the metadata often in the other repo.

**Comment by ama-michelange** [comment]
`package_2` symbol is bad also. It is replaced by `inventory` when displaying.

**Comment by ayuhito** [comment]
I think #902 has fixed this. Can anyone confirm? This may have just been an issue with our website rather than the NPM package itself.

**Comment by ama-michelange** [comment]
With material-symbols-outlined v5.0.17 is ok for trophy and package_2 symbols
Thanks a lot
