### ISSUE TITLE
@fontsource/rubik does not support Arabic

### ISSUE THREAD

**Issue by xuj2017** [DecliningLotus/fontsource#890]
### Describe the bug

l download the Rubik font file(rubik_5.0.9), it includes  Arabic font, like rubik-arabic-xx-xx.woff2; but when l use the @fontsource/rubik node module, l found no arabic in it

### Steps to Reproduce

```
npm install @fontsource/rubik
```
check `node_modules/@fontsource/rubik/files`

### Expected behavior

support arabic in @fontsource/rubik(static fonts)

### Version

12.1

### OS

MacOS

### Browser

Chrome

**Comment by ayuhito** [comment]
Hi @xuj2017, I'm not sure I understand. Looking at the files in the package, it [does still have arabic listed in it](https://www.jsdelivr.com/package/npm/@fontsource/rubik?tab=files&path=files). 

Can you confirm this is still happening as I am unable to reproduce.

**Comment by ayuhito** [comment]
Closed due to lack of reproducibility.
