### ISSUE TITLE
"Application Error" when trying to view Material Symbol fonts

### ISSUE THREAD

**Issue by embostan** [DecliningLotus/fontsource#891]
### Describe the bug

When I try to access the page of any of the Material Symbols fonts (e.g. https://fontsource.org/fonts/material-symbols-rounded), I see that:
![image](https://github.com/fontsource/fontsource/assets/109153151/d6d092a4-dfb4-47ee-aa97-d793fb835461)
![image](https://github.com/fontsource/fontsource/assets/109153151/74c2ba63-b59b-48fa-9453-2fd9f0515e07)

### Steps to Reproduce

1. Go to https://fontsource.org/fonts/material-symbols-rounded

### Expected behavior

I can see the page

### Version

idk

### OS

Windows 10

### Browser

Edge

**Comment by ayuhito** [comment]
Reopening since there is a different error that is also affecting this font.

`{"status":500,"error":"Cannot convert undefined or null to object"}`

**Comment by ayuhito** [comment]
Closed in #909.
