### ISSUE TITLE
Add SCSS with a variable to change the default folder

### ISSUE THREAD

**Issue by Riktastic** [DecliningLotus/fontsource#898]
### Describe the feature you'd like to request

Hi there! Thank you for making my life easier. I've just imported a few fonts into my Hugo library, at first by importing the CSS file into my style.scss. Everything works fine on my homepage, but whenever I access a subdirectory the font fails to resolve.

I've converted the CSS file of two fonts into SCSS files which can be manipulated by setting a variable before importing them. Thus making it easy to change the base URL/base directory.

### Describe the solution you'd like

Add SCSS files to the fonts. Where by each SCSS file has a set of variables that can be manipulated. For example: 
```
/*!
 * FontSource: Work Sans
 */

$fontsource-work-sans-font: "Work Sans Variable" !default;
$fontsource-work-sans-dir: "/fonts/work-sans" !default;

/* work-sans-vietnamese-wght-normal */
@font-face {
  font-family: $fontsource-work-sans-font;
  font-style: normal;
  font-display: swap;
  font-weight: 100 900;
  src: url("#{$fontsource-work-sans-dir}/work-sans-vietnamese-wght-normal.woff2") format('woff2-variations');
  unicode-range: U+0102-0103,U+0110-0111,U+0128-0129,U+0168-0169,U+01A0-01A1,U+01AF-01B0,U+0300-0301,U+0303-0304,U+0308-0309,U+0323,U+0329,U+1EA0-1EF9,U+20>
}
```

### Describe alternatives you've considered

None, due to my choice of web framework (Hugo) I'm limited.

**Comment by jwr1** [comment]
Have you tried using the built-in scss mixins from fontsource? It has an option for setting the directory ([documentation here](https://fontsource.org/docs/getting-started/faces-mixin#mixin-arguments)).

**Comment by Riktastic** [comment]
Great! This was just what I was looking for. Thanks! I was unfamiliar with this practice.
