### ISSUE TITLE
Wrong displaying numbers for font Inter with font-feature-settings: 'frac' 1

### ISSUE THREAD

**Issue by helenjs** [DecliningLotus/fontsource#915]
### Description

I need to use font-feature-settings: 'frac' 1, it should display numbers as normal number, if use 1/3 then 1 should be as superscript and 3 as subscript. But in new version of Inter all numbers displays as superscript <sup>3</sup>, fractions values displays correctly.

Could you help me with that, maybe I import settings wrongly or bug of new version. 

It worked correctly in version 3.0

screenshots are attached

<img width="348" alt="Screenshot 2023-12-14 at 16 24 01" src="https://github.com/fontsource/fontsource/assets/26553645/9b72d7a4-9d16-42fe-9310-b7366412770f">
<img width="271" alt="Screenshot 2023-12-14 at 16 28 03" src="https://github.com/fontsource/fontsource/assets/26553645/df9499bd-2b94-43a0-9aa8-d304b09a64b4">

**Comment by ayuhito** [comment]
I don't believe we support `font-feature-settings`. Fontsource 3 relied on an older Google API that may have supported these features, but unfortunately, the newer APIs don't support it.

 Related issue: #39

**Comment by AlanBreck** [comment]
Could the `Inter` font file be sourced directly from the author instead of the Google API in order to support the `font-feature-settings`?

https://rsms.me/inter/lab/

**Comment by ayuhito** [comment]
Hi! Sorry, but to reduce maintainer burden we don't manually maintain any fonts that Google Fonts already provides. 

Our custom font pipeline also doesn't support variable fonts or automatic language subsetting, so this would end up being a major regression.
