### ISSUE TITLE
License missing from forntsource/inter dependency

### ISSUE THREAD

**Issue by edsonboldrini** [DecliningLotus/fontsource#922]
### Describe the bug

My team have a small widget that we use in our business inside of a [contentstack cms](https://contentstack.com/) and it uses two main dependencies to generate the widget code: venus-components and fontsource/inter. Since we also have some code tools that validate our code before it gets our production stack, these dependencies seem to miss licenses as the tool we use to verify it says that. Btw, we use the [snyk](https://snyk.io/) to validate our code. Below is our validation result after analyzing our code.

![image](https://github.com/fontsource/fontsource/assets/31242886/0594f9e1-1334-446e-afd9-d2fb5948e07b)

How can I solve it? Are you planning to add some license to this font? We want to keep the code as it was because the ui that we accomplished now is what we really want, since this font and components are already used around everything at contentstack. We really appreciate to get it solved as we want to put other widgets with this beautiful combination venus_components + fontsource/inter. Below is our dependencies versions right now. 

<img width="492" alt="image" src="https://github.com/fontsource/fontsource/assets/31242886/dcea3086-be87-4ed8-8b0b-02ee2439b718">

I'm not sure, but maybe changing this dependency to an cdn approach could hide the dependency from our analyzer, but I wasn't able to do it by myself, so if someone could help I'll be appreciate. Thanks in advance.

### Steps to Reproduce

- Create a project in react using vite and add fontsource/inter as your main font.
- Try to pass it into some snyk analisis.

### Expected behavior

Not having license problems.

### Version

5.0.16

### OS

Any

### Browser

Any

### Additional context

No additional context.

**Comment by ayuhito** [comment]
Hi @edsonboldrini,

We include the [OFL 1.1](https://opensource.org/license/ofl-1-1/) license from the original author which is very common for open-source fonts. For example, almost all fonts on Google Fonts use this license and it is safe to use in commercial contexts. I would encourage you to read the license in more detail to ensure it meets your requirements, but it is often a non-issue for companies. I think you just need to update your Snyk policies to allow OFL-1.1.

**Comment by edsonboldrini** [comment]
Thank you @ayuhito, I will try to make this update into my snyk configs, if you see some docs that explains how to solve it, share it here for future visitors of this thread. I'll do the same if I find something.

**Comment by ayuhito** [comment]
I would assume the following docs would cover that:

- https://docs.snyk.io/scan-using-snyk/snyk-open-source/scan-open-source-libraries-and-licenses/snyk-license-compliance-management
- https://docs.snyk.io/scan-using-snyk/policies/license-policies

Feel free to reopen this if you are still experiencing any issues.
