### ISSUE TITLE
Libre Baskerville font missing the italic variant

### ISSUE THREAD

**Issue by wonrax** [DecliningLotus/fontsource#923]
### Describe the feature you'd like to request

The Libre Baskerville font on Fontsource currently doesn't contain the italic variant, which is different than the normal variant with italic font style. For reference, this font on Google Fonts features 3 styles - Regular, Regular Italic and Bold.

References:
https://github.com/impallari/Libre-Baskerville
https://fonts.google.com/specimen/Libre+Baskerville

### Describe the solution you'd like

Add the italic variant.

**Comment by wonrax** [comment]
I just went to look for other fonts and discovered that actually all of them don't have any italic version while the ones on Google Fonts do. This seems to be a larger problem than a single font's mistake.

This is the Playfair Display font with the Regular Italic variant on Google Fonts:
<img width="955" alt="image" src="https://github.com/fontsource/fontsource/assets/28887874/e3d46286-3d83-458f-8fb4-5d9ce73488f1">

And this is the Playfair Display Regular on Fontsource with italic style enabled:
<img width="1230" alt="image" src="https://github.com/fontsource/fontsource/assets/28887874/fe58f265-1761-4471-96ab-ec6a38a778dd">

I don't know why the Fontsource's font curator made the decision to exclude the italic variants when generating and bundling fonts, but for people that use the italic variant for display, this really matters. If you slap a `font-style: italic` on a regular variant, it doesn't look the same as using the italic variant.

**Comment by ayuhito** [comment]
Good catch! This is a bug with the website rather than the actual files itself. We weren't updating the CSS to point to the italic variants when switching the style. I'll look into it.

**Comment by ayuhito** [comment]
This should be fixed with #927. However, just noting that you will notice Libre Baskerville 700 Italic won't load, which is a separate bug tracked in #855 where some fonts support 400, 400i, 700 but not 700i.

**Comment by wonrax** [comment]
Thanks for your work. I think this is why Google Fonts displays all the variants on the same page instead of organizing into categories (i.e. normal and italic).

**Comment by ayuhito** [comment]
Yup, the issue stems deeper for us since our original API implementation didn't consider this to be a possibility, so it's a little difficult to workaround with since our website relies on said API.
