### ISSUE TITLE
Variable Version of Noto Sans not shown on Website

### ISSUE THREAD

**Issue by OfficialCRUGG** [DecliningLotus/fontsource#926]
### Description

The variable version of Noto Sans exists on npm, but isn't reflected on the Website.
https://fontsource.org/fonts/noto-sans/install
https://www.npmjs.com/package/@fontsource-variable/noto-sans

**Comment by ayuhito** [comment]
This should've been fixed with #935 which introduces better cache invalidation to our APIs. Let me know if you're still encountering this!
