### ISSUE TITLE
The font in 4.5 no longer exists in 5.0

### ISSUE THREAD

**Issue by ThibaudAV** [DecliningLotus/fontsource#947]
### Describe the bug

I can't find the font for [this package](https://www.npmjs.com/package/@fontsource/golos-ui) in 5.0.
Is there a reason for this?

### Steps to Reproduce

Go here https://www.npmjs.com/package/@fontsource/golos-ui
and see that there is no version 5.0

### Expected behavior

As a user i expect have same version as here for example : https://www.npmjs.com/package/@fontsource/fira-mono

### Version

5.0

**Comment by ayuhito** [comment]
It seems that it is no longer present on Google Fonts for unknown reasons, thus we no longer mirror it. Perhaps [this](https://github.com/google/fonts/issues/4623#issuecomment-1453911693) is related.

**Comment by ThibaudAV** [comment]
Ok too bad because it's not the same [golos-UI](https://www.paratype.com/fonts/pt/golos-ui) is `uniwidth`
