### ISSUE TITLE
Non-google fonts aren't updated since last year. 

### ISSUE THREAD

**Issue by chee-z1** [DecliningLotus/fontsource#973]
### Description

Non-google fonts like Iosevka or Mononoki aren't updated since last year. For example, Iosevka's latest version is `30.0.1`, but fontsource is currently using `22.1.2` .

**Comment by ayuhito** [comment]
We're open to PRs to keep them updated, but ideally if we want them to remain automatically updated, getting them on Google Fonts is the best solution. 

Another solution is #729 but that isn't super viable to implement until #39 is finished, which is a massive undertaking.

**Comment by ayuhito** [comment]
I'm going to close this since this will be automatically addressed when the above solutions are implemented. Thanks for the report.
