### ISSUE TITLE
Case sensitive directories on Windows

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [DecliningLotus/fontsource#975]
### Describe the bug

When using this repo/package on a Windows host machine, leveraging WSL2, the directory imported is `@fontsource/manrope` but the package itself is configured to be at `@fontsource/Manrope`.

After running `npm install`, if I rename the `manrope` directory to `Manrope`, everything works.

If I don't do this, the package can't be found on my local machine.

### Steps to Reproduce

1. install the package
2. run the app
3. change `manrope` to `Manrope`

### Expected behavior

As a user, I shouldn't have to worry about directory names and their case-sensitivity.

### Version

5.0.4

### OS

Windows WSL2

### Browser

Chrome

**Comment by ayuhito** [comment]
Can you give me an application reproduction? I use WSL2 and haven't experienced this.

**Comment by ayuhito** [comment]
Closing due to lack of reproduction.
