### ISSUE TITLE
@fontsource/material-icons missing default class

### ISSUE THREAD

**Issue by maixuanhan** [DecliningLotus/fontsource#977]
### Describe the bug

Missing definition of class `.material-icons` in the index.css

### Steps to Reproduce

Open index.css.

### Expected behavior

`.material-icons` class

### Version

all

### OS

Windows

### Browser

Chrome

### Additional context

Original font (use by angular MUI): https://fonts.googleapis.com/icon?family=Material+Icons

**Comment by ayuhito** [comment]
Duplicate #976.
