### ISSUE TITLE
"Press Start 2P" not loading

### ISSUE THREAD

**Issue by vdawg-git** [DecliningLotus/fontsource#978]
### Font Name

Press Start 2P

### Link to font source

https://fontsource.org/fonts/press-start-2p

### Link to font license

=

### Additional context

The font will not load, neither over the package install nor over the CDN. 
I followed the instructions and all other fonts work.

**Comment by vdawg-git** [comment]
All other fonts load just fine

Edit: Renaming the font from "Press Start 2P" to "Press Start" works.
I assume the number in the name is not supported

**Comment by ayuhito** [comment]
I cannot reproduce this. Can you provide a minimal reproduction?

**Comment by ayuhito** [comment]
Closed due to lack of reproduction.
